schema: codefly/saas/settings-contribution/v1
namespace: reference
proto-import: codefly/reference/settings/v1/reference_settings.proto
message: codefly.reference.settings.v1.ReferenceSettings
field: {name: reference, number: 1000}
field-range: {start: 1000, end: 1099}
