package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

Registers every Connect (connectrpc.com/connect) service handler derived
from the proto package. Actual per-service adapter types live in
`connect_handlers.go`.

----------------------------------------------------------------- */

import (
	"context"
	"fmt"
	"net/http"

	"connectrpc.com/connect"
	"connectrpc.com/otelconnect"
	"github.com/rs/cors"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	"accounts/pkg/auth"
	"accounts/pkg/business"
)

// ConnectServer serves the Connect, gRPC, and gRPC-Web protocols over HTTP
// on a single port (h2c for non-TLS dev).
type ConnectServer struct {
	config  *Configuration
	grpc    *GrpcServer
	service *business.Service
}

func NewConnectServer(c *Configuration, grpc *GrpcServer) (*ConnectServer, error) {
	if service == nil {
		return nil, fmt.Errorf("business service must be configured before the Connect server")
	}
	return &ConnectServer{
		config:  c,
		grpc:    grpc,
		service: service,
	}, nil
}

func (s *ConnectServer) Run(ctx context.Context) error {
	if s.config.EndpointConnectPort == nil {
		return nil
	}
	port := *s.config.EndpointConnectPort
	fmt.Println("Starting Connect server at", port)

	mux := http.NewServeMux()

	// Auth interceptor — translates `Authorization: Bearer <jwt>` into
	// the wool context keys (UserAuthID/UserID/OrgID) that callerID()
	// reads on every authenticated handler. No-ops for /Authenticate,
	// /Refresh, /Logout, /JWKS. Required when the api is reached
	// directly (e.g. saas-starter frontend → api Connect endpoint with
	// no auth-sidecar in between).
	//
	// The generated entrypoint completes work.go before constructing any
	// listener, and NewConnectServer fails fast if that lifecycle contract is
	// violated. Keep the minter lookup late-bound so tests and controlled key
	// rotation can replace the configured service without rebuilding handlers.

	// otelconnect — extracts W3C traceparent/baggage from the Connect
	// request headers and starts a child span. Same role as
	// otelgrpc.NewServerHandler on the raw-gRPC server, but for the
	// HTTP/Connect path the browser actually uses. No-op when no OTEL
	// TracerProvider is registered (global tracer is a noop). First
	// in the chain so every later interceptor's logs/spans land under
	// the request's trace.
	otelIc, otelErr := otelconnect.NewInterceptor()
	if otelErr != nil {
		return fmt.Errorf("otelconnect: %w", otelErr)
	}

	auth := connect.WithInterceptors(otelIc, connectAuthInterceptor(func() auth.JWTMinter {
		if service == nil {
			return nil
		}
		return service.JWTMinter()
	}), rateLimitInterceptor(rateLimiter))

	// The catalog generator owns complete service registration and compile-time
	// handler-interface assertions. connect_bindings.yaml supplies only the
	// finite implementation source (gRPC adapter, business service, or shared
	// singleton); it cannot add or omit descriptor services.
	registerCatalogConnectServices(mux, s, auth)

	// CORS — required when the FE talks directly to this api (no
	// auth-sidecar in front). Connect-Web preflights every POST
	// because it sends Authorization + Connect-Protocol-Version
	// headers and a non-standard application/connect+* content type;
	// without explicit CORS the browser drops the preflight at 405
	// and every Connect call fails silently.
	//
	corsHandler := cors.New(cors.Options{
		AllowedOrigins: configuredCORSOrigins(),
		AllowedMethods: []string{http.MethodGet, http.MethodPost, http.MethodOptions},
		AllowedHeaders: []string{
			"Authorization",
			"Content-Type",
			"Connect-Protocol-Version",
			"Connect-Timeout-Ms",
			"X-User-Agent",
			"X-Grpc-Web",
			"Grpc-Timeout",
			"Idempotency-Key",
			// W3C trace context — Sentry's browserTracingIntegration
			// stamps these on outgoing fetches so the api can stitch
			// the browser span to the server span (otelconnect picks
			// them off the request headers). Cross-origin preflight
			// silently strips anything not in this list.
			"traceparent",
			"tracestate",
			"baggage",
			// Sentry-specific propagation header (the SDK sends both
			// W3C `baggage` and `sentry-trace` for max compatibility
			// with non-OTel servers). Harmless on the api side; we
			// just need it past CORS.
			"sentry-trace",
		},
		ExposedHeaders: []string{
			"Grpc-Status",
			"Grpc-Message",
			"Grpc-Status-Details-Bin",
			// RateLimit headers — exposed so well-behaved Connect-Web
			// clients can self-throttle before they hit the wall.
			// Without this in CORS, the browser fetch can't read them
			// even though the server sets them.
			"X-RateLimit-Limit",
			"X-RateLimit-Remaining",
			"X-RateLimit-Reset",
			"Retry-After",
		},
		AllowCredentials: true,
		MaxAge:           7200,
	}).Handler(mux)

	server := &http.Server{
		Addr:    fmt.Sprintf(":%d", port),
		Handler: h2c.NewHandler(corsHandler, &http2.Server{}),
	}

	return server.ListenAndServe()
}
