package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

Registers every Connect (connectrpc.com/connect) service handler derived
from the proto package. Actual per-service adapter types live in
`connect_handlers.go`.

----------------------------------------------------------------- */

import (
	"context"
	"fmt"
	"net/http"

	"connectrpc.com/connect"
	"connectrpc.com/otelconnect"
	"github.com/rs/cors"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	"accounts/pkg/auth"
	"accounts/pkg/business"
	"accounts/pkg/gen/genconnect"
)

// ConnectServer serves the Connect, gRPC, and gRPC-Web protocols over HTTP
// on a single port (h2c for non-TLS dev).
type ConnectServer struct {
	config  *Configuration
	grpc    *GrpcServer
	service *business.Service
}

func NewConnectServer(c *Configuration, grpc *GrpcServer) (*ConnectServer, error) {
	return &ConnectServer{
		config:  c,
		grpc:    grpc,
		service: service,
	}, nil
}

func (s *ConnectServer) Run(ctx context.Context) error {
	if s.config.EndpointConnectPort == nil {
		return nil
	}
	port := *s.config.EndpointConnectPort
	fmt.Println("Starting Connect server at", port)

	mux := http.NewServeMux()

	// Auth interceptor — translates `Authorization: Bearer <jwt>` into
	// the wool context keys (UserAuthID/UserID/OrgID) that callerID()
	// reads on every authenticated handler. No-ops for /Authenticate,
	// /Refresh, /Logout, /JWKS. Required when the api is reached
	// directly (e.g. saas-starter frontend → api Connect endpoint with
	// no auth-sidecar in between).
	//
	// Late-bound minter: NewServer + Connect Run() fire from main.go
	// BEFORE work.go calls adapters.WithService, so capturing the
	// minter at construction would deref nil. The closure resolves
	// the package-level `service` at request time instead.

	// otelconnect — extracts W3C traceparent/baggage from the Connect
	// request headers and starts a child span. Same role as
	// otelgrpc.NewServerHandler on the raw-gRPC server, but for the
	// HTTP/Connect path the browser actually uses. No-op when no OTEL
	// TracerProvider is registered (global tracer is a noop). First
	// in the chain so every later interceptor's logs/spans land under
	// the request's trace.
	otelIc, otelErr := otelconnect.NewInterceptor()
	if otelErr != nil {
		return fmt.Errorf("otelconnect: %w", otelErr)
	}

	auth := connect.WithInterceptors(otelIc, connectAuthInterceptor(func() auth.JWTMinter {
		if service == nil {
			return nil
		}
		return service.JWTMinter()
	}), rateLimitInterceptor(rateLimiter))

	// Services backed by existing gRPC Server structs.
	mux.Handle(genconnect.NewUserServiceHandler(&userConnectHandler{inner: s.grpc.User}, auth))
	mux.Handle(genconnect.NewOrganizationServiceHandler(&orgConnectHandler{inner: s.grpc.Org}, auth))
	mux.Handle(genconnect.NewTeamServiceHandler(&teamConnectHandler{inner: s.grpc.Team}, auth))
	mux.Handle(genconnect.NewPermissionServiceHandler(&permConnectHandler{inner: s.grpc.Perm}, auth))
	mux.Handle(genconnect.NewIdentityServiceHandler(&identConnectHandler{inner: s.grpc.Ident}, auth))
	mux.Handle(genconnect.NewAPIKeyServiceHandler(&apiKeyConnectHandler{inner: s.grpc.APIKey}, auth))
	mux.Handle(genconnect.NewAuthServiceHandler(&authConnectHandler{inner: s.grpc.Auth}, auth))
	mux.Handle(genconnect.NewAuditServiceHandler(&auditConnectHandler{inner: s.grpc.Audit}, auth))
	mux.Handle(genconnect.NewInvitationServiceHandler(&invitationConnectHandler{inner: s.grpc.Invitation}, auth))
	mux.Handle(genconnect.NewPlatformAdminServiceHandler(&platformAdminConnectHandler{inner: s.grpc.PlatformAdmin}, auth))
	// IntrospectionService is intentionally unauthenticated — it
	// describes THIS service's API surface (RPCs / RBAC vocab / RLS
	// tables / scopes), not tenant data. No `auth` interceptor, but
	// keep otelIc so introspection calls still land in the trace.
	mux.Handle(genconnect.NewIntrospectionServiceHandler(
		&introspectionConnectHandler{inner: s.grpc.Introspection},
		connect.WithInterceptors(otelIc),
	))

	// CUSTOM: permissionsplugin Connect handlers. Mirrors the
	// plugin loop in server_gen.go. Both protocols share the
	// SAME PrincipalServer / DelegationServer instances via the
	// adapters package singletons — critical for DelegationServer
	// because DecideDelegation populates mintCache and
	// WaitForDelegation reads from it; cross-protocol calls (e.g.
	// approve via gRPC, wait via Connect) only see the token if
	// they hit the same struct. Preserve these lines when
	// regenerating.
	mux.Handle(genconnect.NewPrincipalServiceHandler(&principalConnectHandler{inner: PrincipalSingleton()}, auth))
	mux.Handle(genconnect.NewDelegationServiceHandler(&delegationConnectHandler{inner: DelegationSingleton()}, auth))

	// Services backed directly by business.Service.
	mux.Handle(genconnect.NewWebhookServiceHandler(&webhookConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewAuditExportServiceHandler(&auditExportConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewConsentServiceHandler(&consentConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewNotificationServiceHandler(&notificationConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewOnboardingServiceHandler(&onboardingConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewGDPRServiceHandler(&gdprConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewMFAServiceHandler(&mfaConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewSSOAdminServiceHandler(&ssoAdminConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewUserSettingsServiceHandler(&userSettingsConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewBillingServiceHandler(&billingConnectHandler{svc: s.service}, auth))

	// CORS — required when the FE talks directly to this api (no
	// auth-sidecar in front). Connect-Web preflights every POST
	// because it sends Authorization + Connect-Protocol-Version
	// headers and a non-standard application/connect+* content type;
	// without explicit CORS the browser drops the preflight at 405
	// and every Connect call fails silently.
	//
	// AllowOriginFunc is permissive in dev (any localhost / 127.0.0.1
	// origin). Production deployments put the auth-sidecar in front
	// and don't reach this code path, so a tight allowlist would just
	// cause dev-mode confusion.
	corsHandler := cors.New(cors.Options{
		AllowOriginFunc: func(origin string) bool { return true },
		AllowedMethods:  []string{http.MethodGet, http.MethodPost, http.MethodOptions},
		AllowedHeaders: []string{
			"Authorization",
			"Content-Type",
			"Connect-Protocol-Version",
			"Connect-Timeout-Ms",
			"X-User-Agent",
			"X-Grpc-Web",
			"Grpc-Timeout",
			// W3C trace context — Sentry's browserTracingIntegration
			// stamps these on outgoing fetches so the api can stitch
			// the browser span to the server span (otelconnect picks
			// them off the request headers). Cross-origin preflight
			// silently strips anything not in this list.
			"traceparent",
			"tracestate",
			"baggage",
			// Sentry-specific propagation header (the SDK sends both
			// W3C `baggage` and `sentry-trace` for max compatibility
			// with non-OTel servers). Harmless on the api side; we
			// just need it past CORS.
			"sentry-trace",
		},
		ExposedHeaders: []string{
			"Grpc-Status",
			"Grpc-Message",
			"Grpc-Status-Details-Bin",
			// RateLimit headers — exposed so well-behaved Connect-Web
			// clients can self-throttle before they hit the wall.
			// Without this in CORS, the browser fetch can't read them
			// even though the server sets them.
			"X-RateLimit-Limit",
			"X-RateLimit-Remaining",
			"X-RateLimit-Reset",
			"Retry-After",
		},
		AllowCredentials: true,
		MaxAge:           7200,
	}).Handler(mux)

	server := &http.Server{
		Addr:    fmt.Sprintf(":%d", port),
		Handler: h2c.NewHandler(corsHandler, &http2.Server{}),
	}

	return server.ListenAndServe()
}
