package adapters

import (
	"net/url"
	"os"
	"strings"

	"github.com/rs/cors"
)

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

----------------------------------------------------------------- */

// defaultAllowedOrigins is used when CORS_ALLOWED_ORIGINS is not set.
var defaultAllowedOrigins = []string{
	"http://localhost:3000",
	"http://localhost:21931",
}

func Cors() *cors.Cors {
	return cors.New(cors.Options{
		AllowedOrigins: configuredCORSOrigins(),
		AllowedMethods: []string{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"},
		AllowedHeaders: []string{
			"Authorization",
			"Content-Type",
			"Accept",
			"Origin",
			"X-Requested-With",
			"X-Request-ID",
			"Idempotency-Key",
		},
		AllowCredentials: true,
		// Handle preflight: rs/cors automatically responds to OPTIONS
		// with the correct Access-Control-Allow-* headers when
		// OptionsPassthrough is false (the default).
	})
}

func configuredCORSOrigins() []string {
	origins := append([]string(nil), defaultAllowedOrigins...)
	if env := os.Getenv("CORS_ALLOWED_ORIGINS"); env != "" {
		origins = nil
		for _, o := range strings.Split(env, ",") {
			o = strings.TrimSpace(o)
			if validExactOrigin(o) {
				origins = append(origins, o)
			}
		}
	}
	return origins
}

func validExactOrigin(origin string) bool {
	if origin == "" || strings.ContainsAny(origin, "*\r\n") {
		return false
	}
	u, err := url.Parse(origin)
	if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
		return false
	}
	return u.User == nil && u.Path == "" && u.RawQuery == "" && u.Fragment == ""
}
