package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

Recommendation: create a `rpcs.go` file in the same directory as this file and
implement your APIs there.

----------------------------------------------------------------- */

import (
	"accounts/pkg/auth"
	gen "accounts/pkg/gen/saas/accounts/v1"
	"context"
	"fmt"
	"net"

	"buf.build/go/protovalidate"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"google.golang.org/protobuf/proto"

	"google.golang.org/grpc/reflection"

	wooltel "github.com/codefly-dev/core/wool/otel"
	codefly "github.com/codefly-dev/sdk-go"
	"google.golang.org/grpc"
)

var validator protovalidate.Validator

func init() {
	v, err := protovalidate.New()
	if err != nil {
		panic(fmt.Errorf("failed to create validator: %w", err))
	}
	validator = v
}

func Validate(req proto.Message) error {
	err := validator.Validate(req)
	if err != nil {
		return status.Error(codes.InvalidArgument, err.Error())
	}
	return nil
}

type Configuration struct {
	EndpointGrpcPort    uint16
	EndpointHttpPort    *uint16
	EndpointConnectPort *uint16
}

// UserServer handles UserService RPCs.
type UserServer struct {
	gen.UnsafeUserServiceServer
}

// OrgServer handles OrganizationService RPCs.
type OrgServer struct {
	gen.UnsafeOrganizationServiceServer
}

// TeamServer handles TeamService RPCs.
type TeamServer struct {
	gen.UnsafeTeamServiceServer
}

// PermServer handles PermissionService RPCs.
type PermServer struct {
	gen.UnsafePermissionServiceServer
}

// IdentServer handles IdentityService RPCs.
type IdentServer struct {
	gen.UnsafeIdentityServiceServer
}

// APIKeyServer handles APIKeyService RPCs.
type APIKeyServer struct {
	gen.UnsafeAPIKeyServiceServer
}

// AuthServer handles AuthService RPCs.
type AuthServer struct {
	gen.UnsafeAuthServiceServer
}

// AuditServer handles AuditService RPCs.
type AuditServer struct {
	gen.UnsafeAuditServiceServer
}

// InvitationServer handles InvitationService RPCs.
type InvitationServer struct {
	gen.UnsafeInvitationServiceServer
}

// PlatformAdminServer handles PlatformAdminService RPCs.
type PlatformAdminServer struct {
	gen.UnsafePlatformAdminServiceServer
}

// IntrospectionServer handles IntrospectionService RPCs — the
// service-level catalog (RPCs, RBAC vocab, RLS tables, scopes).
// Public, no auth. Scoped to THIS service (api); module-level view
// is an aggregation concern (CLI / gateway / Mind).
type IntrospectionServer struct {
	gen.UnsafeIntrospectionServiceServer
}

func (s *IntrospectionServer) GetServiceInfo(ctx context.Context, req *gen.GetServiceInfoRequest) (*gen.GetServiceInfoResponse, error) {
	return service.GetServiceInfo(ctx, req)
}

// GrpcServer wraps all service servers and manages the gRPC lifecycle.
type GrpcServer struct {
	User          *UserServer
	Org           *OrgServer
	Team          *TeamServer
	Perm          *PermServer
	Ident         *IdentServer
	APIKey        *APIKeyServer
	Auth          *AuthServer
	MFA           *MFAServer
	Audit         *AuditServer
	Invitation    *InvitationServer
	PlatformAdmin *PlatformAdminServer
	Introspection *IntrospectionServer

	configuration *Configuration
	gRPC          *grpc.Server
	internalGRPC  *grpc.Server
	validator     protovalidate.Validator
}

func (s *UserServer) Version(ctx context.Context, req *gen.VersionRequest) (*gen.VersionResponse, error) {
	if err := Validate(req); err != nil {
		return nil, err
	}
	return &gen.VersionResponse{
		Version: codefly.ServiceVersion(),
	}, nil
}

func NewGrpServer(c *Configuration, opts ...grpc.ServerOption) (*GrpcServer, error) {
	// OTEL stats handler picks up W3C trace context from incoming gRPC metadata.
	// It is a no-op when no OTEL provider is registered.
	opts = append(opts, wooltel.GRPCServerOptions()...)

	// Auth interceptor (mirror of the Connect one in connect_gen.go).
	// Defense-in-depth: even when an auth-gateway is in front and
	// already stamped X-User-Id headers, the api re-validates any
	// `Authorization: Bearer …` it sees so a direct gRPC connection
	// (dev, debugging, misconfig) cannot bypass auth. Late-bound
	// because business.Service is wired after NewGrpServer runs.
	getMinter := func() auth.JWTMinter {
		if service == nil {
			return nil
		}
		return service.JWTMinter()
	}
	authIc := grpcAuthInterceptor(getMinter, rpcExposureTenant)
	streamAuthIc := grpcStreamAuthInterceptor(getMinter, rpcExposureTenant)
	// gRPC rate-limit twin of the Connect interceptor. Same package-
	// level limiter, same key derivation (rateLimitKey reads the
	// wool context after authIc has stamped it).
	rateIc := grpcRateLimitInterceptor()
	opts = append(opts, grpc.ChainUnaryInterceptor(authIc, rateIc))
	opts = append(opts, grpc.ChainStreamInterceptor(streamAuthIc))

	grpcServer := grpc.NewServer(opts...)
	internalOpts := append([]grpc.ServerOption{}, wooltel.GRPCServerOptions()...)
	internalOpts = append(internalOpts,
		grpc.ChainUnaryInterceptor(grpcAuthInterceptor(getMinter, rpcExposureInternal)),
		grpc.ChainStreamInterceptor(grpcStreamAuthInterceptor(getMinter, rpcExposureInternal)),
	)
	internalServer := grpc.NewServer(internalOpts...)
	v, err := protovalidate.New()
	if err != nil {
		return nil, fmt.Errorf("failed to create validator: %w", err)
	}

	s := &GrpcServer{
		User:          &UserServer{},
		Org:           &OrgServer{},
		Team:          &TeamServer{},
		Perm:          &PermServer{},
		Ident:         &IdentServer{},
		APIKey:        &APIKeyServer{},
		Auth:          &AuthServer{},
		MFA:           &MFAServer{},
		Audit:         &AuditServer{},
		Invitation:    &InvitationServer{},
		PlatformAdmin: &PlatformAdminServer{},
		Introspection: &IntrospectionServer{},
		configuration: c,
		gRPC:          grpcServer,
		internalGRPC:  internalServer,
		validator:     v,
	}

	configurePermissionServerKeys()
	registerCatalogGRPCServices(grpcServer, s)
	registerCatalogGRPCServices(internalServer, s)
	// Server reflection enumerates every registered service and message to any
	// caller that can reach the port — a discovery convenience locally, needless
	// recon surface in a deployed environment. Register it only when running
	// locally. This gate is re-applied by hand over the generated scaffold and
	// pinned by a reflection-registration test so a regeneration cannot silently
	// drop it.
	if codefly.IsLocal() {
		reflection.Register(grpcServer)
	}

	return s, nil
}

func (s *GrpcServer) Run(ctx context.Context) error {
	fmt.Println("Starting gRPC server at", s.configuration.EndpointGrpcPort)
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", s.configuration.EndpointGrpcPort))
	if err != nil {
		return fmt.Errorf("failed to listen: %v", err)
	}

	if err := s.gRPC.Serve(lis); err != nil {
		return fmt.Errorf("failed to serve: %s", err)
	}
	return nil
}
