package adapters

import (
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestRESTServeMuxKeepsTheIdentityHeaderMatcher is the REST half of the
// identity-projection gate.
//
// rest_gen.go is generated ("Do not edit this file!"), and the single option
// that carries the caller's credential and the canonical identity headers
// across the transcoding hop lives inside that generated constructor. A
// regeneration that drops it does not break a build or a route: REST simply
// stops forwarding the acting-as subject, and an impersonated request silently
// authorizes as the admin instead of the target — the exact defect the matcher
// exists to close, reintroduced fail-open.
//
// Asserting the matcher function in isolation cannot see that: it stays green
// while the wiring is gone. So this scans the generated source for the option
// actually being passed to runtime.NewServeMux, which is the only fact that
// makes the REST path behave like the direct transports.
func TestRESTServeMuxKeepsTheIdentityHeaderMatcher(t *testing.T) {
	_, thisFile, _, ok := runtime.Caller(0)
	require.True(t, ok)
	source := filepath.Join(filepath.Dir(thisFile), "rest_gen.go")

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, source, nil, 0)
	require.NoError(t, err)

	wired := false
	ast.Inspect(f, func(n ast.Node) bool {
		call, isCall := n.(*ast.CallExpr)
		if !isCall || !isSelector(call.Fun, "runtime", "NewServeMux") {
			return true
		}
		for _, arg := range call.Args {
			option, isCall := arg.(*ast.CallExpr)
			if !isCall || !isSelector(option.Fun, "runtime", "WithIncomingHeaderMatcher") {
				continue
			}
			if len(option.Args) == 1 {
				if name, isIdent := option.Args[0].(*ast.Ident); isIdent && name.Name == "restIdentityHeaderMatcher" {
					wired = true
				}
			}
		}
		return true
	})

	require.True(t, wired,
		"rest_gen.go must pass runtime.WithIncomingHeaderMatcher(restIdentityHeaderMatcher) to runtime.NewServeMux; "+
			"without it the REST transcoding hop drops the acting-as subject, the session and the assurance evidence, "+
			"and an impersonated REST request authorizes as the real actor instead of the effective subject")
}

func isSelector(expr ast.Expr, pkg, name string) bool {
	selector, ok := expr.(*ast.SelectorExpr)
	if !ok || selector.Sel.Name != name {
		return false
	}
	ident, ok := selector.X.(*ast.Ident)
	return ok && ident.Name == pkg
}
