package adapters

// Extra HTTP routes that live ALONGSIDE the grpc-gateway mux.
//
// The generated rest_gen.go mounts a runtime.ServeMux for the strict public
// REST catalog. Some routes don't fit the proto model — specifically
// Stripe webhooks, which need to receive a raw signed body and verify
// an HMAC header. These are registered here and wrapped into the same
// HTTP listener via combineHandlers().
//
// Why not edit rest_gen.go: that file is regenerated by the go-grpc
// agent. This file is hand-written and survives regeneration. The
// one edit to rest_gen.go is a single call to combineHandlers().

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"strings"
	"sync"
	"time"
)

// refreshTokenCookieName is the httpOnly cookie that carries the long-lived
// refresh token. Keeping it OUT of JS-readable storage (localStorage) is the
// whole point — an XSS can no longer exfiltrate a 7-day refresh token.
const refreshTokenCookieName = "codefly_rt"

// refreshTokenCookie is an HTTP middleware that moves the refresh token between
// the auth JSON endpoints and an httpOnly, SameSite=Strict cookie:
//
//   - POST /v1/auth/refresh and POST /v1/auth/logout: when the request body
//     carries no refresh token, the one from the cookie is injected, so the
//     browser never has to hold it.
//   - 2xx responses of every authentication-completing route: the refresh token
//     is lifted out of the JSON body into the cookie and STRIPPED from the body,
//     so JS never sees it.
//   - POST /v1/auth/logout: the cookie is cleared.
//
// SameSite=Strict + the existing credentialed-CORS allowlist is the CSRF
// defense for the (same-origin) refresh call.
func refreshTokenCookie(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path := r.URL.Path
		completesAuthentication := authenticationCompletingRESTPaths[path]
		consumesCookieRefreshToken := cookieRefreshTokenRESTPaths[path]
		isLogout := path == logoutRESTPath

		if !completesAuthentication && !consumesCookieRefreshToken {
			next.ServeHTTP(w, r)
			return
		}

		// Request side: feed the cookie's refresh token into the call when the
		// body doesn't already carry one. Logout needs this as much as refresh
		// does — the browser's logout posts an empty body and the HttpOnly
		// cookie, so without the lift the request failed field validation before
		// Logout ran, leaving the session family and the access token live while
		// the browser's own cookie was cleared.
		if consumesCookieRefreshToken {
			if c, err := r.Cookie(refreshTokenCookieName); err == nil && c.Value != "" {
				r = injectRefreshToken(r, c.Value)
			}
		}

		// Response side: capture so we can lift the refresh token into a cookie.
		rec := &bodyCapture{ResponseWriter: w, status: http.StatusOK}
		next.ServeHTTP(rec, r)

		if isLogout {
			clearRefreshCookie(w)
		}
		body := rec.buf.Bytes()
		if completesAuthentication && rec.status >= 200 && rec.status < 300 {
			if token, stripped, ok := extractAndStripRefreshToken(body); ok {
				setRefreshCookie(w, token)
				body = stripped
			}
		}
		// Content-Length may have changed after stripping; let net/http set it.
		rec.Header().Del("Content-Length")
		rec.flush(w, body)
	})
}

const logoutRESTPath = "/v1/auth/logout"

// authenticationCompletingRESTPaths are the REST routes whose response carries a
// freshly minted refresh token. Every one of them must hand it to the browser as
// a cookie and strip it from the body; a route missing here returns the
// credential as readable content.
//
// TestEveryAuthCompletionCookiesTheRefreshToken derives the same set from the
// service descriptor and fails when the two disagree, so a new route cannot be
// added to the contract and left out here. The WebAuthn completion was exactly
// that: it shares its response message with the TOTP completion, and only the
// TOTP path was listed.
var authenticationCompletingRESTPaths = map[string]bool{
	"/v1/auth/authenticate":          true,
	"/v1/auth/mfa/complete":          true,
	"/v1/auth/mfa/webauthn/complete": true,
	"/v1/auth/refresh":               true,
}

// The refresh cookie is scoped to `/v1/auth`, which is the REST auth surface and
// NOT the Connect procedure prefix (`/saas.accounts.v1.AuthService/…`). A browser
// therefore does not attach it to a Connect call, and that is deliberate: the
// alternative is a cookie scoped to `/`, which would attach the refresh credential
// to every request this origin serves, including the ones the frontend proxies
// onward.
//
// So the journey for a Connect client is defined rather than accidental:
// authenticate over Connect (the response sets the cookie and carries no readable
// token), then REFRESH AND SIGN OUT over REST `/v1/auth/refresh` and
// `/v1/auth/logout`, where the cookie is in scope. The Connect refresh and logout
// still work for a caller that supplies the credential itself — in its body, or as
// an explicit Cookie header — which refreshTokenFromCookie consumes.

// oauthTokenEndpointRESTPath is the one authentication-completing route whose
// response carries the refresh credential in the body, and must.
//
// It is the OAuth 2.1 token endpoint. Its caller is a registered client
// exchanging an authorization code or a refresh token over a back-channel POST,
// not a browser completing a session: RFC 6749 §5.1 defines the response as a
// JSON body with `refresh_token` in it, and a Set-Cookie there reaches no client
// that could use it. The credential it issues is bound to that client's own
// session kind and registry, which is the separate contract the browser's
// session is deliberately not part of.
//
// Named as an exemption rather than simply absent, so the descriptor-derived
// coverage test can require it to be the ONLY one.
const oauthTokenEndpointRESTPath = "/v1/auth/token"

// cookieRefreshTokenRESTPaths are the routes whose refresh-token field is served
// from the cookie when the body does not carry one.
var cookieRefreshTokenRESTPaths = map[string]bool{
	"/v1/auth/refresh": true,
	logoutRESTPath:     true,
}

// bodyCapture buffers the downstream handler's response so the middleware can
// rewrite the body and headers before they reach the client.
type bodyCapture struct {
	http.ResponseWriter
	buf         bytes.Buffer
	status      int
	wroteHeader bool
}

func (b *bodyCapture) WriteHeader(code int) { b.status = code; b.wroteHeader = true }
func (b *bodyCapture) Write(p []byte) (int, error) {
	return b.buf.Write(p)
}

// flush writes the captured (possibly rewritten) response to the real writer.
func (b *bodyCapture) flush(w http.ResponseWriter, body []byte) {
	w.WriteHeader(b.status)
	_, _ = w.Write(body)
}

func injectRefreshToken(r *http.Request, token string) *http.Request {
	var m map[string]any
	if r.Body != nil {
		raw, _ := io.ReadAll(r.Body)
		_ = r.Body.Close()
		if len(bytes.TrimSpace(raw)) > 0 {
			_ = json.Unmarshal(raw, &m)
		}
	}
	if m == nil {
		m = map[string]any{}
	}
	// Cookie is the source of truth — overwrite whatever the body had.
	// Emit only the proto field name. Sending both snake_case and camelCase
	// aliases makes protojson reject the body as a duplicate field.
	delete(m, "refreshToken")
	m["refresh_token"] = token
	out, _ := json.Marshal(m)
	clone := r.Clone(r.Context())
	clone.Body = io.NopCloser(bytes.NewReader(out))
	clone.ContentLength = int64(len(out))
	clone.Header.Set("Content-Type", "application/json")
	return clone
}

// extractAndStripRefreshToken pulls refreshToken/refresh_token out of a JSON
// object and returns the token, the body with those keys removed, and ok.
func extractAndStripRefreshToken(body []byte) (token string, stripped []byte, ok bool) {
	var m map[string]any
	if json.Unmarshal(body, &m) != nil {
		return "", body, false
	}
	for _, k := range []string{"refreshToken", "refresh_token"} {
		if v, present := m[k]; present {
			if s, isStr := v.(string); isStr && s != "" {
				token = s
			}
			delete(m, k)
		}
	}
	if token == "" {
		return "", body, false
	}
	out, err := json.Marshal(m)
	if err != nil {
		return "", body, false
	}
	return token, out, true
}

// allowInsecureRefreshCookie drops Secure from the refresh cookie. It exists for
// one situation: a browser discards a Secure cookie on a plaintext loopback
// origin, so local development would have no session at all.
//
// It is a property of the DEPLOYMENT, and the zero value — every deployed
// environment, since only work.go sets it — keeps Secure. The flag replaces a
// derivation from the request's Host header, which a caller supplies: a request
// arriving at a deployed cell with `Host: localhost` was answered with a cookie
// the browser would then send over plaintext.
var allowInsecureRefreshCookie bool

// SetAllowInsecureRefreshCookie wires the local-development exemption. Call it
// from codefly.IsLocal() only, like SetExposeAuthErrorDetail: it must never be
// true in a deployed environment.
func SetAllowInsecureRefreshCookie(v bool) { allowInsecureRefreshCookie = v }

// secureRefreshCookie reports whether the refresh cookie carries Secure.
func secureRefreshCookie() bool { return !allowInsecureRefreshCookie }

// refreshCookieMaxAgeSeconds matches the refresh-token TTL.
const refreshCookieMaxAgeSeconds = 7 * 24 * 60 * 60

func setRefreshCookie(w http.ResponseWriter, token string) {
	http.SetCookie(w, refreshCookie(token, refreshCookieMaxAgeSeconds))
}

func clearRefreshCookie(w http.ResponseWriter) {
	cleared := refreshCookie("", -1)
	cleared.Expires = time.Unix(0, 0)
	http.SetCookie(w, cleared)
}

// refreshCookie is the one shape the refresh credential is ever handed to a
// browser in: scoped to the auth routes, not script-readable, same-site, and
// transport-protected outside local development.
func refreshCookie(token string, maxAge int) *http.Cookie {
	return &http.Cookie{
		Name:     refreshTokenCookieName,
		Value:    token,
		Path:     "/v1/auth",
		HttpOnly: true,
		Secure:   secureRefreshCookie(),
		SameSite: http.SameSiteStrictMode,
		MaxAge:   maxAge,
	}
}

var (
	extraRoutesMu sync.RWMutex
	extraRoutes   = map[string]http.Handler{}
)

// RegisterHTTPRoute installs an HTTP handler at the given path. It
// wins over the grpc-gateway mux whenever the request path starts
// with the given prefix.
//
// Call from work.go after constructing the
// handler and BEFORE adapters.NewServer().Run(). Intended for
// webhook endpoints that don't fit the proto model.
func RegisterHTTPRoute(path string, h http.Handler) {
	extraRoutesMu.Lock()
	defer extraRoutesMu.Unlock()
	extraRoutes[path] = h
}

// combineHandlers wraps the grpc-gateway mux so that registered extra
// routes take precedence. Called from rest_gen.go's Run() via a one-
// line edit that survives regeneration by a marker comment.
func combineHandlers(gwMux http.Handler) http.Handler {
	dispatch := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		extraRoutesMu.RLock()
		var match http.Handler
		for prefix, h := range extraRoutes {
			if strings.HasPrefix(r.URL.Path, prefix) {
				match = h
				break
			}
		}
		extraRoutesMu.RUnlock()

		if match != nil {
			match.ServeHTTP(w, r)
			return
		}
		gwMux.ServeHTTP(w, r)
	})
	// consumeHeaderJWTLogin runs first so the gateway-injected identity header is
	// resolved into the login credential before grpc-gateway transcodes the body.
	// Wrap with the refresh-token cookie middleware so the long-lived refresh
	// token lives in an httpOnly cookie instead of the JS-readable response body.
	return consumeHeaderJWTLogin(refreshTokenCookie(dispatch))
}

// consumeHeaderJWTLogin makes the configured gateway-injected identity header
// the single source of the header-jwt login credential on the REST surface.
//
// The browser logs in via POST /v1/auth/authenticate, which grpc-gateway
// (rest_gen.go) serves. grpc-gateway forwards only a fixed header allowlist into
// gRPC metadata (CustomHeaderToGRPCMetadataAnnotator), so the configured header
// never reaches the downstream connect handler on this path — consumption has to
// happen here, at the raw HTTP request. This middleware also strips any
// client-supplied credential from the body, so a caller cannot smuggle a forged
// header_jwt token (which perimeter-trust decode accepts without a signature
// check) past the gateway that is supposed to own the header.
func consumeHeaderJWTLogin(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if headerJWTLoginHeader == "" || r.Method != http.MethodPost || r.URL.Path != "/v1/auth/authenticate" {
			next.ServeHTTP(w, r)
			return
		}
		next.ServeHTTP(w, rewriteHeaderJWTBody(r, headerJWTLoginHeader))
	})
}

// rewriteHeaderJWTBody returns a clone of r whose JSON body carries the
// header_jwt credential taken exclusively from the named request header. Any
// client-supplied authentication credential is removed first: in header-jwt mode
// the login route's credential is the header and nothing else. When the header
// is absent the body is left credential-less, so grpc-gateway's oneof-required
// validation rejects the request rather than trusting a client-supplied token.
func rewriteHeaderJWTBody(r *http.Request, header string) *http.Request {
	var raw []byte
	if r.Body != nil {
		raw, _ = io.ReadAll(r.Body)
		_ = r.Body.Close()
	}

	var m map[string]json.RawMessage
	if len(bytes.TrimSpace(raw)) > 0 {
		if err := json.Unmarshal(raw, &m); err != nil {
			// Not a JSON object we can rewrite; forward unchanged and let
			// grpc-gateway reject it.
			clone := r.Clone(r.Context())
			clone.Body = io.NopCloser(bytes.NewReader(raw))
			clone.ContentLength = int64(len(raw))
			return clone
		}
	}
	if m == nil {
		m = map[string]json.RawMessage{}
	}

	// Emit only proto field names — sending a snake_case and camelCase alias for
	// the same field makes protojson reject the body as a duplicate.
	for _, k := range []string{"header_jwt", "headerJwt", "oauth_code", "oauthCode", "fixture"} {
		delete(m, k)
	}
	if token := r.Header.Get(header); token != "" {
		cred, _ := json.Marshal(map[string]string{"token": token})
		m["header_jwt"] = cred
	}

	out, _ := json.Marshal(m)
	clone := r.Clone(r.Context())
	clone.Body = io.NopCloser(bytes.NewReader(out))
	clone.ContentLength = int64(len(out))
	clone.Header.Set("Content-Type", "application/json")
	return clone
}
