package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

----------------------------------------------------------------- */

import (
	"context"
	"fmt"
	"net/http"
	"strings"
	"time"

	"google.golang.org/grpc/status"

	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"

	"github.com/codefly-dev/core/wool"
	"github.com/google/uuid"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

type RestServer struct {
	config *Configuration
	grpc   *GrpcServer
}

func NewRestServer(c *Configuration, grpc *GrpcServer) (*RestServer, error) {
	server := &RestServer{config: c, grpc: grpc}
	return server, nil
}

func CustomHeaderToGRPCMetadataAnnotator(ctx context.Context, req *http.Request) metadata.MD {
	return wool.MetadataFromRequest(ctx, req)
}

func customErrorHandler(ctx context.Context, mux *runtime.ServeMux, marshaler runtime.Marshaler, w http.ResponseWriter, r *http.Request, err error) {
	if runtime.HTTPStatusFromCode(status.Code(err)) == http.StatusNotFound {
		http.Error(w, "Route not found", http.StatusNotFound)
		return
	}
	runtime.DefaultHTTPErrorHandler(ctx, mux, marshaler, w, r, err)
}

func (s *RestServer) Run(ctx context.Context) error {
	fmt.Println("Starting REST + internal gRPC server at", *s.config.EndpointHttpPort)
	if s.config.EndpointConnectPort == nil {
		return fmt.Errorf("REST transcoding requires the generated Connect/gRPC endpoint")
	}

	c := Cors()

	gwMux := runtime.NewServeMux(
		runtime.WithMetadata(CustomHeaderToGRPCMetadataAnnotator),
		runtime.WithErrorHandler(customErrorHandler))

	opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}
	// Connect-Go serves Connect, gRPC, and gRPC-Web for all catalog services on
	// one port. grpc-gateway speaks gRPC to that complete generated surface; the
	// legacy raw-gRPC port intentionally remains the private/internal listener.
	endpoint := fmt.Sprintf("0.0.0.0:%d", *s.config.EndpointConnectPort)

	if err := registerCatalogRESTHandlers(ctx, gwMux, endpoint, opts); err != nil {
		return err
	}

	// CUSTOM: combineHandlers mounts non-proto HTTP routes (e.g. Stripe
	// webhooks) alongside the grpc-gateway mux. See rest_extras.go.
	// Preserve this line when regenerating.
	restHandler := c.Handler(combineHandlers(catalogRESTHandler(gwMux)))
	handler := multiplexInternalGRPC(s.grpc.internalGRPC, logRequestOutcome(restHandler))
	server := &http.Server{
		Addr:    fmt.Sprintf(":%d", *s.config.EndpointHttpPort),
		Handler: h2c.NewHandler(handler, &http2.Server{}),
	}
	return server.ListenAndServe()
}

func multiplexInternalGRPC(internal *grpc.Server, fallback http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.ProtoMajor == 2 && strings.HasPrefix(strings.ToLower(r.Header.Get("Content-Type")), "application/grpc") {
			internal.ServeHTTP(w, r)
			return
		}
		fallback.ServeHTTP(w, r)
	})
}

type logResponseWriter struct {
	http.ResponseWriter
	statusCode  int
	wroteHeader bool
}

func (rsp *logResponseWriter) WriteHeader(code int) {
	if rsp.wroteHeader {
		return
	}
	rsp.wroteHeader = true
	rsp.statusCode = code
	rsp.ResponseWriter.WriteHeader(code)
}

func (rsp *logResponseWriter) Unwrap() http.ResponseWriter {
	return rsp.ResponseWriter
}

func newLogResponseWriter(w http.ResponseWriter) *logResponseWriter {
	return &logResponseWriter{ResponseWriter: w, statusCode: http.StatusOK}
}

type httpFailureDiagnostic struct {
	RequestID  string
	Method     string
	Path       string
	StatusCode int
	Duration   time.Duration
}

var emitHTTPFailureDiagnostic = func(d httpFailureDiagnostic) {
	grpclog.Errorf(
		"http request failed request_id=%q method=%q path=%q status=%d duration_ms=%d",
		d.RequestID, d.Method, d.Path, d.StatusCode, d.Duration.Milliseconds(),
	)
}

func logRequestOutcome(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requestID := trustedRequestID(r.Header.Get("X-Request-Id"))
		if requestID == "" {
			requestID = uuid.NewString()
		}
		w.Header().Set("X-Request-Id", requestID)
		r.Header.Set("X-Request-Id", requestID)

		lw := newLogResponseWriter(w)
		started := time.Now()
		h.ServeHTTP(lw, r)

		if lw.statusCode >= http.StatusBadRequest {
			emitHTTPFailureDiagnostic(httpFailureDiagnostic{
				RequestID:  requestID,
				Method:     r.Method,
				Path:       boundedLogValue(r.URL.Path, 256),
				StatusCode: lw.statusCode,
				Duration:   time.Since(started),
			})
		}
	})
}

func trustedRequestID(candidate string) string {
	if candidate == "" || len(candidate) > 128 {
		return ""
	}
	for _, r := range candidate {
		if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
			(r >= '0' && r <= '9') || r == '-' || r == '_' || r == '.') {
			return ""
		}
	}
	return candidate
}

func boundedLogValue(value string, limit int) string {
	value = strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return -1
		}
		return r
	}, value)
	if len(value) > limit {
		return value[:limit]
	}
	return value
}
