package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!


----------------------------------------------------------------- */

import (
	"context"
	"fmt"

	"google.golang.org/grpc"
)

type Server struct {
	Grpc    *GrpcServer
	Rest    *RestServer
	Connect *ConnectServer
}

func NewServer(config *Configuration, grpcOpts ...grpc.ServerOption) (*Server, error) {

	grpc, err := NewGrpServer(config, grpcOpts...)
	if err != nil {
		return nil, err
	}

	var rest *RestServer
	if config.EndpointHttpPort != nil {
		rest, err = NewRestServer(config, grpc)
		if err != nil {
			return nil, err
		}
	}

	var conn *ConnectServer
	if config.EndpointConnectPort != nil {
		conn, err = NewConnectServer(config, grpc)
		if err != nil {
			return nil, err
		}
	}

	return &Server{
		Grpc:    grpc,
		Rest:    rest,
		Connect: conn,
	}, nil
}

func (server *Server) Start(ctx context.Context) error {
	if server.Rest != nil {
		go func() {
			err := server.Rest.Run(ctx)
			if err != nil {
				panic(err)
			}
		}()
	}
	if server.Connect != nil {
		go func() {
			err := server.Connect.Run(ctx)
			if err != nil {
				panic(err)
			}
		}()
	}
	return server.Grpc.Run(ctx)
}

func (server *Server) Stop() {
	fmt.Println("Stopping server...")
	server.Grpc.gRPC.GracefulStop()
	server.Grpc.internalGRPC.GracefulStop()
}
