// CODE GENERATED by scripts/generate-plugin-registry.mjs — DO NOT EDIT.
//
// Every AdminPlugin under src/plugins/ is auto-discovered here, so adding a
// plugin file (e.g. a side-module's admin console) registers it with no edits
// to admin-config.ts or any other base file. Regenerated by predev/prebuild/
// pretest; coverage is enforced by __tests__/registry.test.ts.
import type { AdminPlugin } from "@/lib/admin-core";
import * as p0 from "./audit";
import * as p1 from "./core-users";
import * as p2 from "./platform-admin";

function pick(mod: Record<string, unknown>): AdminPlugin | undefined {
  return Object.values(mod).find(
    (v): v is AdminPlugin =>
      !!v && typeof v === "object" && typeof (v as { name?: unknown }).name === "string",
  );
}

export const discoveredPlugins: AdminPlugin[] = [p0, p1, p2]
  .map(pick)
  .filter((p): p is AdminPlugin => p !== undefined);
