// CODE GENERATED by scripts/generate-plugin-registry.mjs — DO NOT EDIT.
//
// Discovered AdminPlugins: the starter's own under src/plugins/, plus any
// PROJECT plugins from SAAS_PROJECT_PLUGINS_DIR (a consumer's local dir outside
// this tree). Adding a plugin needs no edits here — regenerated by predev/
// prebuild/pretest; coverage enforced by __tests__/registry.test.ts.
import type { AdminPlugin } from "@/lib/admin-core";
import * as p0 from "./audit";
import * as p1 from "./core-users";
import * as p2 from "./platform-admin";

function pick(mod: Record<string, unknown>): AdminPlugin | undefined {
  return Object.values(mod).find(
    (v): v is AdminPlugin =>
      !!v && typeof v === "object" && typeof (v as { name?: unknown }).name === "string",
  );
}

export const discoveredPlugins: AdminPlugin[] = [p0, p1, p2]
  .map(pick)
  .filter((p): p is AdminPlugin => p !== undefined);
