// Code generated by codefly agent. DO NOT EDIT.
//
// This file is regenerated from plugins.yaml by the codefly agent
// during Sync. The current contents reflect the YAML state and
// match what the regenerator produces — hand-edits made here are
// expected to survive regeneration as long as plugins.yaml stays
// in sync.
package plugins

import (
	"accounts/pkg/framework"
	"accounts/pkg/permissionsplugin"
)

// All returns the list of registered plugins.
//
// **Wiring note for operators.** The permissions plugin is
// constructed without signing keys here so registry_gen.go has
// no dependency on operator config. main.go (or work.go) is
// responsible for replacing the bare instance with one that has
// keys via Plugin.WithHMACSecret / Plugin.WithEd25519Key.
//
// Pattern in main.go:
//
//	for _, p := range plugins.All() {
//	    if perm, ok := p.(*permissionsplugin.Plugin); ok {
//	        perm.WithHMACSecret(loadSpawnSecret())
//	        perm.WithEd25519Key(loadEd25519PrivateKey())
//	    }
//	}
//	server, _ := adapters.NewServer(config, ...)
func All() []framework.Plugin {
	return []framework.Plugin{
		permissionsplugin.New(),
	}
}
