package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

Registers every Connect (connectrpc.com/connect) service handler derived
from the proto package. Actual per-service adapter types live in
`connect_handlers.go`.

----------------------------------------------------------------- */

import (
	"context"
	"fmt"
	"net/http"

	"connectrpc.com/connect"
	"github.com/rs/cors"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	"api/pkg/auth"
	"api/pkg/business"
	"api/pkg/gen/genconnect"
)

// ConnectServer serves the Connect, gRPC, and gRPC-Web protocols over HTTP
// on a single port (h2c for non-TLS dev).
type ConnectServer struct {
	config  *Configuration
	grpc    *GrpcServer
	service *business.Service
}

func NewConnectServer(c *Configuration, grpc *GrpcServer) (*ConnectServer, error) {
	return &ConnectServer{
		config:  c,
		grpc:    grpc,
		service: service,
	}, nil
}

func (s *ConnectServer) Run(ctx context.Context) error {
	if s.config.EndpointConnectPort == nil {
		return nil
	}
	port := *s.config.EndpointConnectPort
	fmt.Println("Starting Connect server at", port)

	mux := http.NewServeMux()

	// Auth interceptor — translates `Authorization: Bearer <jwt>` into
	// the wool context keys (UserAuthID/UserID/OrgID) that callerID()
	// reads on every authenticated handler. No-ops for /Authenticate,
	// /Refresh, /Logout, /JWKS. Required when the api is reached
	// directly (e.g. saas-starter frontend → api Connect endpoint with
	// no auth-sidecar in between).
	//
	// Late-bound minter: NewServer + Connect Run() fire from main.go
	// BEFORE work.go calls adapters.WithService, so capturing the
	// minter at construction would deref nil. The closure resolves
	// the package-level `service` at request time instead.
	auth := connect.WithInterceptors(connectAuthInterceptor(func() auth.JWTMinter {
		if service == nil {
			return nil
		}
		return service.JWTMinter()
	}), rateLimitInterceptor(rateLimiter))

	// Services backed by existing gRPC Server structs.
	mux.Handle(genconnect.NewUserServiceHandler(&userConnectHandler{inner: s.grpc.User}, auth))
	mux.Handle(genconnect.NewOrganizationServiceHandler(&orgConnectHandler{inner: s.grpc.Org}, auth))
	mux.Handle(genconnect.NewTeamServiceHandler(&teamConnectHandler{inner: s.grpc.Team}, auth))
	mux.Handle(genconnect.NewPermissionServiceHandler(&permConnectHandler{inner: s.grpc.Perm}, auth))
	mux.Handle(genconnect.NewIdentityServiceHandler(&identConnectHandler{inner: s.grpc.Ident}, auth))
	mux.Handle(genconnect.NewAPIKeyServiceHandler(&apiKeyConnectHandler{inner: s.grpc.APIKey}, auth))
	mux.Handle(genconnect.NewAuthServiceHandler(&authConnectHandler{inner: s.grpc.Auth}, auth))
	mux.Handle(genconnect.NewAuditServiceHandler(&auditConnectHandler{inner: s.grpc.Audit}, auth))
	mux.Handle(genconnect.NewInvitationServiceHandler(&invitationConnectHandler{inner: s.grpc.Invitation}, auth))
	mux.Handle(genconnect.NewPlatformAdminServiceHandler(&platformAdminConnectHandler{inner: s.grpc.PlatformAdmin}, auth))

	// Services backed directly by business.Service.
	mux.Handle(genconnect.NewWebhookServiceHandler(&webhookConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewAuditExportServiceHandler(&auditExportConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewNotificationServiceHandler(&notificationConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewOnboardingServiceHandler(&onboardingConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewGDPRServiceHandler(&gdprConnectHandler{svc: s.service}, auth))
	mux.Handle(genconnect.NewMFAServiceHandler(&mfaConnectHandler{svc: s.service}, auth))

	// CORS — required when the FE talks directly to this api (no
	// auth-sidecar in front). Connect-Web preflights every POST
	// because it sends Authorization + Connect-Protocol-Version
	// headers and a non-standard application/connect+* content type;
	// without explicit CORS the browser drops the preflight at 405
	// and every Connect call fails silently.
	//
	// AllowOriginFunc is permissive in dev (any localhost / 127.0.0.1
	// origin). Production deployments put the auth-sidecar in front
	// and don't reach this code path, so a tight allowlist would just
	// cause dev-mode confusion.
	corsHandler := cors.New(cors.Options{
		AllowOriginFunc: func(origin string) bool { return true },
		AllowedMethods:  []string{http.MethodGet, http.MethodPost, http.MethodOptions},
		AllowedHeaders: []string{
			"Authorization",
			"Content-Type",
			"Connect-Protocol-Version",
			"Connect-Timeout-Ms",
			"X-User-Agent",
			"X-Grpc-Web",
			"Grpc-Timeout",
		},
		ExposedHeaders: []string{
			"Grpc-Status",
			"Grpc-Message",
			"Grpc-Status-Details-Bin",
		},
		AllowCredentials: true,
		MaxAge:           7200,
	}).Handler(mux)

	server := &http.Server{
		Addr:    fmt.Sprintf(":%d", port),
		Handler: h2c.NewHandler(corsHandler, &http2.Server{}),
	}

	return server.ListenAndServe()
}
