package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

----------------------------------------------------------------- */

import (
	"context"
	"fmt"
	"net/http"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
)

// ConnectServer serves the Connect, gRPC, and gRPC-Web protocols over HTTP.
// It handles all three protocols on a single port.
//
// Once `codefly generate proto` runs and creates the genconnect package,
// register each service handler on the mux in Run().
type ConnectServer struct {
	config *Configuration
}

func NewConnectServer(c *Configuration) (*ConnectServer, error) {
	return &ConnectServer{config: c}, nil
}

func (s *ConnectServer) Run(ctx context.Context) error {
	if s.config.EndpointConnectPort == nil {
		return nil
	}
	port := *s.config.EndpointConnectPort
	fmt.Println("Starting Connect server at", port)

	mux := http.NewServeMux()

	// TODO: After running `codefly generate proto`, import the genconnect
	// package and register each service handler:
	//
	//   import "api/pkg/gen/genconnect"
	//
	//   path, handler := genconnect.NewUserServiceHandler(&userConnectHandler{})
	//   mux.Handle(path, handler)
	//   path, handler = genconnect.NewOrganizationServiceHandler(&orgConnectHandler{})
	//   mux.Handle(path, handler)
	//   ... etc for each proto service

	// Use h2c for HTTP/2 without TLS (development mode)
	server := &http.Server{
		Addr:    fmt.Sprintf(":%d", port),
		Handler: h2c.NewHandler(mux, &http2.Server{}),
	}

	return server.ListenAndServe()
}
