package adapters

// Extra HTTP routes that live ALONGSIDE the grpc-gateway mux.
//
// The generated rest_gen.go mounts a runtime.ServeMux that serves every
// proto RPC. Some routes don't fit the proto model — specifically
// Stripe webhooks, which need to receive a raw signed body and verify
// an HMAC header. These are registered here and wrapped into the same
// HTTP listener via combineHandlers().
//
// Why not edit rest_gen.go: that file is regenerated by the go-grpc
// agent. This file is hand-written and survives regeneration. The
// one edit to rest_gen.go is a single call to combineHandlers().

import (
	"net/http"
	"strings"
	"sync"
)

var (
	extraRoutesMu sync.RWMutex
	extraRoutes   = map[string]http.Handler{}
)

// RegisterHTTPRoute installs an HTTP handler at the given path. It
// wins over the grpc-gateway mux whenever the request path starts
// with the given prefix.
//
// Call from work.go / cmd/local/main.go AFTER constructing the
// handler and BEFORE adapters.NewServer().Run(). Intended for
// webhook endpoints that don't fit the proto model.
func RegisterHTTPRoute(path string, h http.Handler) {
	extraRoutesMu.Lock()
	defer extraRoutesMu.Unlock()
	extraRoutes[path] = h
}

// combineHandlers wraps the grpc-gateway mux so that registered extra
// routes take precedence. Called from rest_gen.go's Run() via a one-
// line edit that survives regeneration by a marker comment.
func combineHandlers(gwMux http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		extraRoutesMu.RLock()
		var match http.Handler
		for prefix, h := range extraRoutes {
			if strings.HasPrefix(r.URL.Path, prefix) {
				match = h
				break
			}
		}
		extraRoutesMu.RUnlock()

		if match != nil {
			match.ServeHTTP(w, r)
			return
		}
		gwMux.ServeHTTP(w, r)
	})
}
