DROP POLICY IF EXISTS team_members_tenant ON team_members;
ALTER TABLE team_members NO FORCE ROW LEVEL SECURITY;
ALTER TABLE team_members DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS teams_tenant ON teams;
ALTER TABLE teams NO FORCE ROW LEVEL SECURITY;
ALTER TABLE teams DISABLE ROW LEVEL SECURITY;
