-- Restore the broad pre-63 request-role grants.

GRANT SELECT, INSERT, UPDATE, DELETE ON
    api_keys,
    audit_events,
    audit_export_configs,
    entitlement_overrides,
    gdpr_requests,
    invitations,
    magic_links,
    mfa_backup_codes,
    mfa_devices,
    mfa_login_transactions,
    notifications,
    onboarding_progress,
    org_settings,
    organization_members,
    organizations,
    principals,
    role_assignments,
    role_permissions,
    roles,
    sessions,
    subscriptions,
    team_members,
    teams,
    usage_events,
    usage_totals,
    user_identities,
    users,
    webauthn_ceremonies,
    webauthn_credentials,
    webhook_deliveries,
    webhook_subscriptions
TO app_tenant;
