// Code generated by protoc-gen-codefly-facade-go from saas.accounts.v1. DO NOT EDIT.

package accounts

import (
	context "context"
	http "net/http"

	connect "connectrpc.com/connect"
	v1 "github.com/codefly-dev/module-saas-starter/libraries/source-read-sdk/go/gen/saas/accounts/v1"
	accountsv1connect "github.com/codefly-dev/module-saas-starter/libraries/source-read-sdk/go/gen/saas/accounts/v1/accountsv1connect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Gateway is the minimal surface this facade needs from the solution runtime.
type Gateway interface {
	BaseURL() string
	HTTPClient() *http.Client
}

// Client is the entry point: New(gw).<Service>().<Rpc>(ctx, req).
type Client struct {
	gw   Gateway
	opts []connect.ClientOption
}

// New binds the facade to a gateway. Extra connect.ClientOptions are
// forwarded to every sub-client.
func New(gw Gateway, opts ...connect.ClientOption) *Client {
	return &Client{gw: gw, opts: append(opts, connect.WithGRPC())}
}

// ModuleCapabilities returns the typed ModuleCapabilitiesService facade.
func (c *Client) ModuleCapabilities() *ModuleCapabilitiesClient {
	return &ModuleCapabilitiesClient{inner: accountsv1connect.NewModuleCapabilitiesServiceClient(c.gw.HTTPClient(), c.gw.BaseURL(), c.opts...)}
}

// ModuleCapabilitiesClient wraps the generated ModuleCapabilitiesServiceClient and hides the
// connect.Request/Response envelope.
type ModuleCapabilitiesClient struct {
	inner accountsv1connect.ModuleCapabilitiesServiceClient
}

func (a *ModuleCapabilitiesClient) GetCurrentInstallation(ctx context.Context, req *v1.ModuleCurrentInstallationRequest) (*v1.ModuleCurrentInstallationResponse, error) {
	resp, err := a.inner.GetCurrentInstallation(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) ApproveExecutableArtifact(ctx context.Context, req *v1.ModuleExecutableArtifactRequest) (*v1.ModuleExecutableArtifactResponse, error) {
	resp, err := a.inner.ApproveExecutableArtifact(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) AuthorizeExecutableArtifact(ctx context.Context, req *v1.ModuleExecutableArtifactRequest) (*v1.ModuleExecutableArtifactResponse, error) {
	resp, err := a.inner.AuthorizeExecutableArtifact(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) RevokeExecutableArtifact(ctx context.Context, req *v1.ModuleRevokeExecutableArtifactRequest) (*v1.ModuleExecutableArtifactResponse, error) {
	resp, err := a.inner.RevokeExecutableArtifact(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) ExchangeDelegatedReadAudience(ctx context.Context, req *v1.ModuleExchangeDelegatedReadAudienceRequest) (*v1.IssuedWorkContext, error) {
	resp, err := a.inner.ExchangeDelegatedReadAudience(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) ExchangeDelegatedOperationAudience(ctx context.Context, req *v1.ModuleExchangeDelegatedOperationAudienceRequest) (*v1.IssuedWorkContext, error) {
	resp, err := a.inner.ExchangeDelegatedOperationAudience(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) CheckWorkContextRecordAccess(ctx context.Context, req *v1.CheckWorkContextRecordAccessRequest) (*v1.CheckWorkContextRecordAccessResponse, error) {
	resp, err := a.inner.CheckWorkContextRecordAccess(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) ListReadableSourceCollections(ctx context.Context, req *v1.ListReadableSourceCollectionsRequest) (*v1.ListReadableSourceCollectionsResponse, error) {
	resp, err := a.inner.ListReadableSourceCollections(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) PlaceRecord(ctx context.Context, req *v1.ModulePlaceRecordRequest) (*v1.ModulePlaceRecordResponse, error) {
	resp, err := a.inner.PlaceRecord(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) EnqueueJob(ctx context.Context, req *v1.ModuleEnqueueJobRequest) (*v1.ModuleEnqueueJobResponse, error) {
	resp, err := a.inner.EnqueueJob(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) ClaimJobs(ctx context.Context, req *v1.ModuleClaimJobsRequest) (*v1.ModuleClaimJobsResponse, error) {
	resp, err := a.inner.ClaimJobs(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) HeartbeatJob(ctx context.Context, req *v1.ModuleHeartbeatJobRequest) (*v1.ModuleHeartbeatJobResponse, error) {
	resp, err := a.inner.HeartbeatJob(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) AckJob(ctx context.Context, req *v1.ModuleAckJobRequest) (*emptypb.Empty, error) {
	resp, err := a.inner.AckJob(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) NackJob(ctx context.Context, req *v1.ModuleNackJobRequest) (*emptypb.Empty, error) {
	resp, err := a.inner.NackJob(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) NotifyUser(ctx context.Context, req *v1.ModuleNotifyUserRequest) (*v1.ModuleNotifyUserResponse, error) {
	resp, err := a.inner.NotifyUser(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) NotifyOrgAdmins(ctx context.Context, req *v1.ModuleNotifyOrgAdminsRequest) (*v1.ModuleNotifyOrgAdminsResponse, error) {
	resp, err := a.inner.NotifyOrgAdmins(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) RequestApproval(ctx context.Context, req *v1.ModuleRequestApprovalRequest) (*v1.ModuleRequestApprovalResponse, error) {
	resp, err := a.inner.RequestApproval(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) GetApproval(ctx context.Context, req *v1.ModuleGetApprovalRequest) (*v1.ModuleApproval, error) {
	resp, err := a.inner.GetApproval(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) CancelApproval(ctx context.Context, req *v1.ModuleCancelApprovalRequest) (*emptypb.Empty, error) {
	resp, err := a.inner.CancelApproval(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) EmitAuditEvent(ctx context.Context, req *v1.ModuleEmitAuditEventRequest) (*emptypb.Empty, error) {
	resp, err := a.inner.EmitAuditEvent(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) DeclareAuditEventTypes(ctx context.Context, req *v1.ModuleDeclareAuditEventTypesRequest) (*v1.ModuleDeclareAuditEventTypesResponse, error) {
	resp, err := a.inner.DeclareAuditEventTypes(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) ListSubjectVisibility(ctx context.Context, req *v1.ModuleListSubjectVisibilityRequest) (*v1.ModuleListSubjectVisibilityResponse, error) {
	resp, err := a.inner.ListSubjectVisibility(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

// skipped: streaming RPC FetchDatasourceBlob

// skipped: streaming RPC FetchDatasourceFiles

func (a *ModuleCapabilitiesClient) MintModuleRegistration(ctx context.Context, req *v1.ModuleMintRegistrationRequest) (*v1.ModuleMintRegistrationResponse, error) {
	resp, err := a.inner.MintModuleRegistration(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) MintSolutionRegistration(ctx context.Context, req *v1.SolutionMintRegistrationRequest) (*v1.SolutionMintRegistrationResponse, error) {
	resp, err := a.inner.MintSolutionRegistration(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) MintModuleWorkContext(ctx context.Context, req *v1.ModuleMintWorkContextRequest) (*v1.ModuleMintWorkContextResponse, error) {
	resp, err := a.inner.MintModuleWorkContext(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) MintModuleOperationContext(ctx context.Context, req *v1.ModuleMintOperationContextRequest) (*v1.ModuleMintOperationContextResponse, error) {
	resp, err := a.inner.MintModuleOperationContext(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) MintSourceOperationContext(ctx context.Context, req *v1.ModuleMintSourceOperationContextRequest) (*v1.ModuleMintSourceOperationContextResponse, error) {
	resp, err := a.inner.MintSourceOperationContext(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) PublishEvent(ctx context.Context, req *v1.ModulePublishEventRequest) (*v1.ModulePublishEventResponse, error) {
	resp, err := a.inner.PublishEvent(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) Subscribe(ctx context.Context, req *v1.ModuleSubscribeRequest) (*v1.ModuleSubscribeResponse, error) {
	resp, err := a.inner.Subscribe(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) Unsubscribe(ctx context.Context, req *v1.ModuleUnsubscribeRequest) (*emptypb.Empty, error) {
	resp, err := a.inner.Unsubscribe(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) ListSubscriptions(ctx context.Context, req *v1.ModuleListSubscriptionsRequest) (*v1.ModuleListSubscriptionsResponse, error) {
	resp, err := a.inner.ListSubscriptions(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (a *ModuleCapabilitiesClient) ReplayEvents(ctx context.Context, req *v1.ModuleReplayEventsRequest) (*v1.ModuleReplayEventsResponse, error) {
	resp, err := a.inner.ReplayEvents(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}
