#!/usr/bin/env bash
# The hosted CI runner is Linux x64. Keep the release and archive digest paired.
set -euo pipefail

version="${CODEFLY_VERSION:-0.1.180}"
case "${version}" in
  0.1.145)
    checksum=a6e1a0e7f4adae8b2701dcea7e05cb03f1ac49c85ee96b4ac98dd2fa20dcc4c7
    ;;
  0.1.151)
    # First release with the integrity-input classification for the planner;
    # its build and sync-drift phases dereference a nil Runner (cli#705).
    checksum=eca1e72c8fca8d61626ea8a9f0a969f47d4a64871ffca25b3355e068f009706c
    ;;
  0.1.155)
    # Carries cli#706 (the nil-Runner fix) and cli#704 (`publish clients`);
    # its Core 0.3.35 runtime requires the agent fleet pinned at Core >= 0.3.28.
    # (0.3.35 is what the released archive vendors — `go version -m codefly`.)
    checksum=1cd0ce2abad4b4b0f19ea3ac16ca7ac92b5112082518590a3f4e9a76f5bcd3fa
    ;;
  0.1.160)
    # Requires CLI-agent protocol v1 from every service agent (Core 0.5 fleet):
    # go-grpc >= 0.1.43, nextjs >= 0.0.157, postgres >= 0.0.137, redis >= 0.0.92,
    # vault >= 0.0.33. Refuses the previous pins outright.
    checksum=7d68805935e942309406aeec385ea2f3135fa9a6fec06760df6b2370ff48b5c1
    ;;
  0.1.161)
    # Core v0.5.1: `latest` resolves to the newest published release (cli#785);
    # cli#786 removed `codefly verify`, `codefly sync module` and the `verify`
    # CI phase, so this tree carries no base manifest and plans `sync-drift` alone.
    checksum=47e133cebd8f72fc44e2c1c3f76b375377ba946818fcbbdcee1f126c12a7fd5c
    ;;
  0.1.162)
    # cli#799: committed `module-resolution`, CODEFLY_MODULE_CACHE, per-module
    # render namespaces; `generate contracts` skips an exported REST endpoint
    # that carries no OpenAPI document instead of failing, which is what lets
    # this tree export the gateway's REST endpoint at all.
    checksum=9ffdb661f448332c8a0edab90c16006683289ce51f97c9067de8e974e8bdb679
    ;;
  0.1.168)
    # Core v0.5.9: the GitOps render classifies configuration names by their
    # carrier (cli#826), environments admit a configuration profile chain
    # (cli#827), and workspace endpoint references resolve per consumer and
    # order the run (cli#828).
    checksum=d8c6180afdd4ca9b393d0bf5d5a7974c20fa1047023f31c1f03100465889cc02
    ;;
  0.1.171)
    # Raises the host's build-recipe support from docker-build-recipe/v3 to v4,
    # which is what lets this tree run a released go-grpc or nextjs agent at all:
    # every agent from go-grpc 0.1.48-dev.42ce38050224 and nextjs 0.0.162 onward
    # advertises v3, v4 and v5, and 0.1.168 verified the plan against v3 alone.
    # Core supports artifact-execution/v1, runtime-init-dependency-mappings/v1,
    # codefly.dev/docker-build-recipe/v4 and configuration-value-template/v1.
    checksum=0bdb109784b9835bea984a94ddb9a809c8c29f0e260c59f821a637cbff464ffe
    ;;
  0.1.179)
    # The pin the committed generated bytes are actually produced by, which is
    # the point of moving it: `generate proto`, `generate contracts` and the
    # saas-sdk client all stamp their generator, and until now CI reproduced
    # none of them — main's own library.codefly.yaml says 0.1.178 against a
    # 0.1.171 pin, so the inconsistency predates this branch and sync-drift was
    # red on a diff nobody could explain.
    #
    # Nothing else moves with it. Core's build-recipe support is unchanged from
    # 0.1.171 — it still tops out at codefly.dev/docker-build-recipe/v4, read
    # off the v0.1.179 release's own agent-requirements — so no service-agent
    # pin changes, and the one functional difference (cli#911, the workspace
    # resolver registered where every command's context is born) only helps a
    # solution composed against this host resolve.
    checksum=6e7666ef095815a77c10fb1644c69e17b0e8869476c18713bfaa496971b5c45f
    ;;
  0.1.180)
    # THE FIRST RELEASE THAT VENDORS CORE v0.14.0 (cli#914, tag bb5b14f5).
    #
    # It is what makes the declarations this repository now authors loadable at
    # all: v0.14.0 refuses `allow-modules` on an export by name — an allow-list is
    # derived from the consumers' declared service dependencies, never written by
    # the module it would grant — and requires `exposure` on a public endpoint.
    #
    # IT MOVES IN ITS OWN PR, AFTER the declarations, and the order is forced.
    # `codefly ci plan` runs with `--base ${CODEFLY_BASE}` and at this version
    # loads the BASE revision's workspace as well as the head, so while the base
    # still authored the nine wildcards the plan step failed on the BASE whatever
    # the head looked like. The declarations had to reach main first; only then do
    # base and head both load under v0.14.0 and the gate pass.
    #
    # Verified rather than taken from the release notes: `go version -m` on this
    # exact archive reports `codefly-dev/core v0.14.0` and
    # `sdk-go/workcontext v0.0.0-20261007042459-a9cae91487bc`, and the checksum
    # below is the line in the release's own checksums.txt.
    checksum=af63538645fe092dfcf2fdec3887532db1bd58507295d1f126ddec4fa351c6db
    ;;
  *)
    echo "Unsupported Codefly CI version: ${version}" >&2
    exit 1
    ;;
esac

if [[ "$(uname -s)" != Linux || "$(uname -m)" != x86_64 ]]; then
  echo 'The CI Codefly installer requires Linux x64' >&2
  exit 1
fi

archive="codefly_${version}_linux_amd64.tar.gz"
scratch="$(mktemp -d)"
trap 'rm -rf "${scratch}"' EXIT

curl --fail --silent --show-error --location --retry 3 --retry-all-errors \
  "https://github.com/codefly-dev/cli/releases/download/v${version}/${archive}" \
  --output "${scratch}/${archive}"
printf '%s  %s\n' "${checksum}" "${scratch}/${archive}" | sha256sum -c -
tar -xzf "${scratch}/${archive}" -C "${scratch}" codefly
install -d "${RUNNER_TEMP}/codefly-bin"
install -m 755 "${scratch}/codefly" "${RUNNER_TEMP}/codefly-bin/codefly"
echo "${RUNNER_TEMP}/codefly-bin" >> "${GITHUB_PATH}"
