// Code generated by module-compose. DO NOT EDIT.
package settingscatalog

type Field struct {
	Namespace string
	Name      string
	Number    int
	Message   string
}

var fields = [...]Field{}

func Fields() []Field {
	return append([]Field(nil), fields[:]...)
}
