package cataloggen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"sort"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"gopkg.in/yaml.v3"

	"accounts/pkg/business"
	catalogv1 "accounts/pkg/gen/saas/catalog/v1"
)

const connectBindingsVersion = "v1"

type connectBindings struct {
	Version  string                    `yaml:"version"`
	Services map[string]connectBinding `yaml:"services"`
}

type connectBinding struct {
	Handler    string               `yaml:"handler"`
	Source     connectBindingSource `yaml:"source"`
	GRPCServer string               `yaml:"grpc_server,omitempty"`
}

type connectBindingSource struct {
	Kind string `yaml:"kind"`
	Name string `yaml:"name,omitempty"`
}

// RenderConnectRegistration joins the descriptor-owned service catalog with a
// finite dependency-injection binding file and emits compile-time checked
// Connect registration. The binding file cannot contain raw Go expressions.
func RenderConnectRegistration(catalogDocument, bindingDocument []byte) ([]byte, error) {
	catalog, bindings, err := decodeRegistrationInputs(catalogDocument, bindingDocument)
	if err != nil {
		return nil, err
	}

	var source strings.Builder
	source.WriteString(`// Code generated by cmd/connect-registration from generated/service-catalog.json and connect_bindings.yaml. DO NOT EDIT.

package adapters

import (
	"net/http"

	"connectrpc.com/connect"

	genconnect "accounts/pkg/gen/saas/accounts/v1/accountsv1connect"
)

// Compile-time assertions keep every configured adapter aligned with the
// descriptor-generated Connect handler interface.
var (
`)
	for _, service := range catalog.GetServices() {
		binding := bindings.Services[service.GetName()]
		fmt.Fprintf(&source, "\t_ genconnect.%sHandler = (*%s)(nil)\n", service.GetName(), binding.Handler)
	}
	source.WriteString(`)

// registerCatalogConnectServices registers every catalog service on one mux.
// Exact procedure paths remain owned by protoc-gen-connect-go.
func registerCatalogConnectServices(mux *http.ServeMux, server *ConnectServer, options ...connect.HandlerOption) {
`)
	for _, service := range catalog.GetServices() {
		binding := bindings.Services[service.GetName()]
		fmt.Fprintf(&source, "\tmux.Handle(genconnect.New%sHandler(&%s{%s}, options...))\n",
			service.GetName(), binding.Handler, bindingInitializer(binding.Source))
	}
	source.WriteString("}\n")

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated Connect registration: %w", err)
	}
	return formatted, nil
}

// RenderGRPCRegistration derives the transitional raw-gRPC registration from
// the same complete catalog and finite implementation binding as Connect. A
// grpc source is already a generated gRPC implementation; a singleton source
// is required to return one. Business sources are Connect-native and remain on
// the catalog-complete Connect/gRPC/gRPC-Web listener until P1-NET-001 retires
// the legacy raw-gRPC listener.
func RenderGRPCRegistration(catalogDocument, bindingDocument []byte) ([]byte, error) {
	catalog, bindings, err := decodeRegistrationInputs(catalogDocument, bindingDocument)
	if err != nil {
		return nil, err
	}

	var source strings.Builder
	source.WriteString(`// Code generated by cmd/connect-registration from generated/service-catalog.json and connect_bindings.yaml. DO NOT EDIT.

package adapters

import (
	"google.golang.org/grpc"

	gen "accounts/pkg/gen/saas/accounts/v1"
)

// registerCatalogGRPCServices registers every catalog service backed by a
// native gRPC implementation. Connect-native business handlers are served by
// the catalog-complete Connect listener and are intentionally omitted here.
func registerCatalogGRPCServices(registrar grpc.ServiceRegistrar, server *GrpcServer) {
`)
	for _, service := range catalog.GetServices() {
		binding := bindings.Services[service.GetName()]
		if initializer, ok := grpcBindingInitializer(binding); ok {
			fmt.Fprintf(&source, "\tgen.Register%sServer(registrar, %s)\n", service.GetName(), initializer)
		}
	}
	source.WriteString("}\n\n")

	source.WriteString("var catalogGRPCServiceNames = []string{\n")
	for _, service := range catalog.GetServices() {
		if _, ok := grpcBindingInitializer(bindings.Services[service.GetName()]); !ok {
			continue
		}
		fmt.Fprintf(&source, "\t%q,\n", service.GetFullName())
	}
	source.WriteString("}\n\n")

	source.WriteString("var catalogConnectOnlyServiceNames = []string{\n")
	for _, service := range catalog.GetServices() {
		if _, ok := grpcBindingInitializer(bindings.Services[service.GetName()]); ok {
			continue
		}
		fmt.Fprintf(&source, "\t%q,\n", service.GetFullName())
	}
	source.WriteString("}\n")

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated gRPC registration: %w", err)
	}
	return formatted, nil
}

func decodeRegistrationInputs(catalogDocument, bindingDocument []byte) (*catalogv1.ServiceCatalog, connectBindings, error) {
	catalog := &catalogv1.ServiceCatalog{}
	if err := (protojson.UnmarshalOptions{DiscardUnknown: false}).Unmarshal(catalogDocument, catalog); err != nil {
		return nil, connectBindings{}, fmt.Errorf("decode service catalog: %w", err)
	}
	if err := business.ValidateServiceCatalog(catalog); err != nil {
		return nil, connectBindings{}, fmt.Errorf("validate service catalog: %w", err)
	}

	bindings, err := decodeConnectBindings(bindingDocument)
	if err != nil {
		return nil, connectBindings{}, err
	}
	if err := validateConnectBindingCoverage(catalog, bindings); err != nil {
		return nil, connectBindings{}, err
	}
	return catalog, bindings, nil
}

func decodeConnectBindings(document []byte) (connectBindings, error) {
	var bindings connectBindings
	decoder := yaml.NewDecoder(bytes.NewReader(document))
	decoder.KnownFields(true)
	if err := decoder.Decode(&bindings); err != nil {
		return connectBindings{}, fmt.Errorf("decode Connect bindings: %w", err)
	}
	if bindings.Version != connectBindingsVersion {
		return connectBindings{}, fmt.Errorf("unsupported Connect bindings version %q", bindings.Version)
	}
	if len(bindings.Services) == 0 {
		return connectBindings{}, fmt.Errorf("no services in Connect bindings")
	}
	return bindings, nil
}

func validateConnectBindingCoverage(catalog *catalogv1.ServiceCatalog, bindings connectBindings) error {
	wanted := make(map[string]struct{}, len(catalog.GetServices()))
	for _, service := range catalog.GetServices() {
		name := service.GetName()
		wanted[name] = struct{}{}
		binding, exists := bindings.Services[name]
		if !exists {
			return fmt.Errorf("missing Connect binding for catalog service %q", name)
		}
		if !token.IsIdentifier(binding.Handler) {
			return fmt.Errorf("invalid handler identifier %q for Connect service %q", binding.Handler, name)
		}
		switch binding.Source.Kind {
		case "business":
			if binding.Source.Name != "" {
				return fmt.Errorf("business source of Connect service %q must not declare a name", name)
			}
		case "grpc", "singleton":
			if !token.IsIdentifier(binding.Source.Name) {
				return fmt.Errorf("invalid %s source name %q for Connect service %q", binding.Source.Kind, binding.Source.Name, name)
			}
		default:
			return fmt.Errorf("unsupported source kind %q for Connect service %q", binding.Source.Kind, name)
		}
		if binding.GRPCServer != "" {
			if binding.Source.Kind != "business" {
				return fmt.Errorf("grpc_server on Connect service %q is allowed only for a business source", name)
			}
			if !token.IsIdentifier(binding.GRPCServer) {
				return fmt.Errorf("invalid grpc_server %q for Connect service %q", binding.GRPCServer, name)
			}
		}
	}

	var extras []string
	for service := range bindings.Services {
		if _, exists := wanted[service]; !exists {
			extras = append(extras, service)
		}
	}
	if len(extras) > 0 {
		sort.Strings(extras)
		return fmt.Errorf("services in Connect bindings are absent from the catalog: %s", strings.Join(extras, ", "))
	}
	return nil
}

func bindingInitializer(source connectBindingSource) string {
	switch source.Kind {
	case "business":
		return "svc: server.service"
	case "grpc":
		return "inner: server.grpc." + source.Name
	case "singleton":
		return "inner: " + source.Name + "()"
	default:
		panic("validated Connect binding source kind became invalid")
	}
}

func grpcBindingInitializer(binding connectBinding) (string, bool) {
	if binding.GRPCServer != "" {
		return "server." + binding.GRPCServer, true
	}
	switch binding.Source.Kind {
	case "grpc":
		return "server." + binding.Source.Name, true
	case "singleton":
		return binding.Source.Name + "()", true
	case "business":
		return "", false
	default:
		panic("validated Connect binding source kind became invalid")
	}
}
