package cataloggen

import (
	"fmt"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"google.golang.org/protobuf/encoding/protojson"

	"accounts/pkg/business"
	catalogv1 "accounts/pkg/gen/saas/catalog/v1"
)

var typescriptIdentifierPattern = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// RenderFrontendCatalog emits the transport-neutral TypeScript client factory
// and the permission/entitlement vocabulary consumed by the frontend and
// compile-time plugins. Protobuf message/service descriptors remain generated
// by protoc-gen-es; this artifact joins them through the normalized catalog.
func RenderFrontendCatalog(catalogDocument []byte) ([]byte, error) {
	catalog := &catalogv1.ServiceCatalog{}
	if err := (protojson.UnmarshalOptions{DiscardUnknown: false}).Unmarshal(catalogDocument, catalog); err != nil {
		return nil, fmt.Errorf("decode service catalog: %w", err)
	}
	if err := business.ValidateServiceCatalog(catalog); err != nil {
		return nil, fmt.Errorf("validate service catalog: %w", err)
	}

	serviceImports, err := frontendServiceImports(catalog)
	if err != nil {
		return nil, err
	}
	permissionIdentifiers, err := permissionConstantIdentifiers(catalog.GetPermissions())
	if err != nil {
		return nil, err
	}
	entitlementIdentifiers, err := entitlementConstantIdentifiers(catalog.GetEntitlements())
	if err != nil {
		return nil, err
	}

	var source strings.Builder
	source.WriteString(`// Code generated by cmd/frontend-catalog from generated/service-catalog.json. DO NOT EDIT.

import { createClient, type Client, type Transport } from "@connectrpc/connect";
`)
	for _, module := range sortedImportModules(serviceImports) {
		fmt.Fprintf(&source, "import { %s } from %s;\n", strings.Join(serviceImports[module], ", "), quoteTS(module))
	}

	source.WriteString("\nexport const PERMISSIONS = {\n")
	for _, permission := range catalog.GetPermissions() {
		fmt.Fprintf(&source, "  %s: %s,\n", permissionIdentifiers[permission.GetPermission()], quoteTS(permission.GetPermission()))
	}
	source.WriteString(`} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
`)

	resources, actions := permissionSegments(catalog.GetPermissions(), false)
	fmt.Fprintf(&source, "export type PermissionResource = %s;\n", typescriptUnion(resources))
	fmt.Fprintf(&source, "export type PermissionAction = %s;\n", typescriptUnion(actions))
	source.WriteString("export type PermissionGrant = Permission | `${PermissionResource}:*` | `*:${PermissionAction}`;\n\n")

	source.WriteString(`export interface PermissionDefinition {
  readonly resource: string;
  readonly action: string;
  readonly description: string;
  readonly builtInRoles: readonly string[];
  readonly apiKeyScope: boolean;
}

export const PERMISSION_DEFINITIONS: Readonly<Record<Permission, PermissionDefinition>> = {
`)
	for _, permission := range catalog.GetPermissions() {
		fmt.Fprintf(&source, "  [PERMISSIONS.%s]: { resource: %s, action: %s, description: %s, builtInRoles: %s, apiKeyScope: %t },\n",
			permissionIdentifiers[permission.GetPermission()], quoteTS(permission.GetResource()), quoteTS(permission.GetAction()),
			quoteTS(permission.GetDescription()), typescriptStringArray(permission.GetBuiltInRoles()), permission.GetApiKeyScope())
	}
	source.WriteString(`};

const permissionValues: readonly string[] = Object.values(PERMISSIONS);
const permissionSet = new Set<string>(permissionValues);

export function isPermission(value: string): value is Permission {
  return permissionSet.has(value);
}

`)

	source.WriteString("export const API_KEY_SCOPES = [\n")
	for _, permission := range catalog.GetPermissions() {
		if permission.GetApiKeyScope() {
			fmt.Fprintf(&source, "  PERMISSIONS.%s,\n", permissionIdentifiers[permission.GetPermission()])
		}
	}
	source.WriteString(`] as const;

export type APIKeyScope = (typeof API_KEY_SCOPES)[number];
`)
	scopeResources, scopeActions := permissionSegments(catalog.GetPermissions(), true)
	fmt.Fprintf(&source, "export type APIKeyScopeResource = %s;\n", typescriptUnion(scopeResources))
	fmt.Fprintf(&source, "export type APIKeyScopeAction = %s;\n", typescriptUnion(scopeActions))
	source.WriteString("export type APIKeyScopeGrant = APIKeyScope | `${APIKeyScopeResource}:*` | `*:${APIKeyScopeAction}`;\n\n")

	source.WriteString("export const ENTITLEMENTS = {\n")
	for _, entitlement := range catalog.GetEntitlements() {
		fmt.Fprintf(&source, "  %s: %s,\n", entitlementIdentifiers[entitlement.GetKey()], quoteTS(entitlement.GetKey()))
	}
	source.WriteString(`} as const;

export type Entitlement = (typeof ENTITLEMENTS)[keyof typeof ENTITLEMENTS];
export type EntitlementKind = "feature" | "quota";

export interface EntitlementDefinition {
  readonly kind: EntitlementKind;
  readonly unit: string;
  readonly description: string;
}

export const ENTITLEMENT_DEFINITIONS: Readonly<Record<Entitlement, EntitlementDefinition>> = {
`)
	for _, entitlement := range catalog.GetEntitlements() {
		kind, err := entitlementKindName(entitlement.GetKind())
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&source, "  [ENTITLEMENTS.%s]: { kind: %s, unit: %s, description: %s },\n",
			entitlementIdentifiers[entitlement.GetKey()], quoteTS(kind), quoteTS(entitlement.GetUnit()), quoteTS(entitlement.GetDescription()))
	}
	source.WriteString(`};

const entitlementValues: readonly string[] = Object.values(ENTITLEMENTS);
const entitlementSet = new Set<string>(entitlementValues);

export function isEntitlement(value: string): value is Entitlement {
  return entitlementSet.has(value);
}

`)

	source.WriteString("export const ACCOUNT_SERVICE_DESCRIPTORS = {\n")
	for _, service := range catalog.GetServices() {
		fmt.Fprintf(&source, "  %s,\n", service.GetName())
	}
	source.WriteString(`} as const;

export type AccountServiceName = keyof typeof ACCOUNT_SERVICE_DESCRIPTORS;

export interface AccountsClients {
`)
	for _, service := range catalog.GetServices() {
		fmt.Fprintf(&source, "  readonly %s: Client<typeof %s>;\n", service.GetName(), service.GetName())
	}
	source.WriteString(`}

export function createAccountsClients(transport: Transport): AccountsClients {
  return {
`)
	for _, service := range catalog.GetServices() {
		fmt.Fprintf(&source, "    %s: createClient(%s, transport),\n", service.GetName(), service.GetName())
	}
	source.WriteString(`  };
}
`)
	return []byte(source.String()), nil
}

func frontendServiceImports(catalog *catalogv1.ServiceCatalog) (map[string][]string, error) {
	methodSource := make(map[string]string, len(catalog.GetServices()))
	for _, method := range catalog.GetMethods() {
		if previous, exists := methodSource[method.GetFullService()]; exists && previous != method.GetSourceProto() {
			return nil, fmt.Errorf("service %q spans TypeScript source modules %q and %q", method.GetFullService(), previous, method.GetSourceProto())
		}
		methodSource[method.GetFullService()] = method.GetSourceProto()
	}

	imports := make(map[string][]string)
	for _, service := range catalog.GetServices() {
		if !typescriptIdentifierPattern.MatchString(service.GetName()) {
			return nil, fmt.Errorf("service %q is not a TypeScript identifier", service.GetName())
		}
		sourceProto := methodSource[service.GetFullName()]
		if sourceProto == "" {
			return nil, fmt.Errorf("service %q has no source proto", service.GetFullName())
		}
		if path.Dir(sourceProto) != "saas/accounts/v1" || path.Ext(sourceProto) != ".proto" {
			return nil, fmt.Errorf("service %q source %q is outside the generated accounts TypeScript package", service.GetFullName(), sourceProto)
		}
		module := "./" + strings.TrimSuffix(path.Base(sourceProto), ".proto") + "_pb"
		imports[module] = append(imports[module], service.GetName())
	}
	for module := range imports {
		sort.Strings(imports[module])
	}
	return imports, nil
}

func sortedImportModules(imports map[string][]string) []string {
	modules := make([]string, 0, len(imports))
	for module := range imports {
		modules = append(modules, module)
	}
	sort.Strings(modules)
	return modules
}

func permissionConstantIdentifiers(definitions []*catalogv1.PermissionDefinition) (map[string]string, error) {
	identifiers := make(map[string]string, len(definitions))
	seen := make(map[string]string, len(definitions))
	for _, definition := range definitions {
		identifier := constantIdentifier(definition.GetPermission())
		if definition.GetPermission() == "*:*" {
			identifier = "ALL"
		}
		if previous, exists := seen[identifier]; exists {
			return nil, fmt.Errorf("permissions %q and %q collide on TypeScript identifier %q", previous, definition.GetPermission(), identifier)
		}
		seen[identifier] = definition.GetPermission()
		identifiers[definition.GetPermission()] = identifier
	}
	return identifiers, nil
}

func entitlementConstantIdentifiers(definitions []*catalogv1.EntitlementDefinition) (map[string]string, error) {
	identifiers := make(map[string]string, len(definitions))
	seen := make(map[string]string, len(definitions))
	for _, definition := range definitions {
		identifier := constantIdentifier(definition.GetKey())
		if previous, exists := seen[identifier]; exists {
			return nil, fmt.Errorf("entitlements %q and %q collide on TypeScript identifier %q", previous, definition.GetKey(), identifier)
		}
		seen[identifier] = definition.GetKey()
		identifiers[definition.GetKey()] = identifier
	}
	return identifiers, nil
}

func constantIdentifier(value string) string {
	var out strings.Builder
	separator := false
	for _, character := range value {
		if unicode.IsLetter(character) || unicode.IsDigit(character) {
			if separator && out.Len() > 0 {
				out.WriteByte('_')
			}
			separator = false
			out.WriteRune(unicode.ToUpper(character))
		} else {
			separator = true
		}
	}
	return out.String()
}

func permissionSegments(definitions []*catalogv1.PermissionDefinition, scopesOnly bool) ([]string, []string) {
	resourceSet := make(map[string]struct{})
	actionSet := make(map[string]struct{})
	for _, definition := range definitions {
		if scopesOnly && !definition.GetApiKeyScope() {
			continue
		}
		if definition.GetResource() != "*" {
			resourceSet[definition.GetResource()] = struct{}{}
		}
		if definition.GetAction() != "*" {
			actionSet[definition.GetAction()] = struct{}{}
		}
	}
	resources := setKeys(resourceSet)
	actions := setKeys(actionSet)
	return resources, actions
}

func setKeys(values map[string]struct{}) []string {
	out := make([]string, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func typescriptUnion(values []string) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, quoteTS(value))
	}
	if len(parts) == 0 {
		return "never"
	}
	return strings.Join(parts, " | ")
}

func typescriptStringArray(values []string) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, quoteTS(value))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func quoteTS(value string) string {
	return strconv.Quote(value)
}

func entitlementKindName(kind catalogv1.EntitlementKind) (string, error) {
	switch kind {
	case catalogv1.EntitlementKind_ENTITLEMENT_KIND_FEATURE:
		return "feature", nil
	case catalogv1.EntitlementKind_ENTITLEMENT_KIND_QUOTA:
		return "quota", nil
	default:
		return "", fmt.Errorf("unsupported entitlement kind %s", kind)
	}
}
