import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
	DASHBOARD_CATALOG,
	DASHBOARD_CATALOG_ID,
	DASHBOARD_CATALOG_PROTOCOL_VERSION,
	DASHBOARD_COMPONENT,
	DASHBOARD_DATA_SCHEMA,
	DASHBOARD_DATA_SCHEMA_ID,
	DASHBOARD_GRID_COMPONENT,
	DASHBOARD_VISUALIZATIONS,
	DASHBOARD_WIDGET_COMPONENT_BY_VISUALIZATION,
	dashboardCatalogComponents,
	type JsonSchemaNode,
} from "../catalog.js";
import { fromDashboardData } from "../types.js";
import type { DashboardView, WidgetVisualization } from "../types.js";

// What the kit publishes, held to what the kit has. The compile-time half of
// this contract is in `catalog.ts` itself — a `DashboardView` field or a
// `WidgetVisualization` member that the documents do not describe fails to build
// — so these are the things a type cannot state: the committed bytes, A2UI's own
// rules about a catalog document, and whether the view model the kit renders
// actually validates against the schema it ships.

// Same cwd-relative candidate trick as `package-contract.test.ts`: this spec runs
// under the kit's own Vitest project and under the host's, with different cwds.
function documentBytes(name: string): string {
	for (const prefix of ["src/dashboard", "packages/codefly-ui/src/dashboard"]) {
		try {
			return readFileSync(`${prefix}/${name}`, "utf8");
		} catch {
			// Not this cwd — try the next candidate.
		}
	}
	throw new Error(`could not locate ${name}`);
}

const serialize = (document: unknown) =>
	`${JSON.stringify(document, null, "\t")}\n`;

// A2UI v1.0 §catalog: no other top-level keys are permitted, and `$defs` may hold
// only these two.
const PERMITTED_ROOT_KEYS = [
	"$schema",
	"$id",
	"protocolVersion",
	"title",
	"description",
	"catalogId",
	"instructions",
	"components",
	"functions",
	"$defs",
];
const PERMITTED_DEFS = ["anyComponent", "anyFunction"];

// The specification's component-name rule as the consumer that freezes a catalog
// narrows it: UAX #31 restricted to ASCII, because the name travels into a frozen
// artifact subject whose bytes are compared.
const IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;

// The type name A2UI reserves for the container a renderer instantiates itself.
const RESERVED_COMPONENT = "Surface";

const components = DASHBOARD_CATALOG.components as Record<string, JsonSchemaNode>;
const entries = Object.entries(components);

function propertiesOf(entry: JsonSchemaNode): Record<string, JsonSchemaNode> {
	return (entry.properties ?? {}) as Record<string, JsonSchemaNode>;
}

describe("the published documents are the generated bytes", () => {
	// Hand-edit either document and it stops being a function of the types that
	// gate it, so this is the same comparison `--check` makes, inside the suite.
	it("ships the catalog exactly as catalog.ts renders it", () => {
		expect(documentBytes("dashboard.catalog.generated.json")).toBe(
			serialize(DASHBOARD_CATALOG),
		);
	});

	it("ships the data model exactly as catalog.ts renders it", () => {
		expect(documentBytes("dashboard-data.schema.generated.json")).toBe(
			serialize(DASHBOARD_DATA_SCHEMA),
		);
	});
});

describe("the catalog is an A2UI catalog document", () => {
	it("carries only permitted root keys", () => {
		expect(
			Object.keys(DASHBOARD_CATALOG).filter(
				(key) => !PERMITTED_ROOT_KEYS.includes(key),
			),
		).toEqual([]);
	});

	it("keeps $defs to anyComponent and anyFunction", () => {
		expect(
			Object.keys(DASHBOARD_CATALOG.$defs).filter(
				(key) => !PERMITTED_DEFS.includes(key),
			),
		).toEqual([]);
	});

	it("identifies itself the same way twice, at the pinned protocol version", () => {
		// `$id` should be the `catalogId`: a consumer's envelope carries the
		// second, a renderer resolves refs against the first, and a mismatch is
		// a surface refused at admission.
		expect(DASHBOARD_CATALOG.$id).toBe(DASHBOARD_CATALOG_ID);
		expect(DASHBOARD_CATALOG.catalogId).toBe(DASHBOARD_CATALOG_ID);
		expect(DASHBOARD_CATALOG.protocolVersion).toBe("0.9");
		expect(DASHBOARD_CATALOG_PROTOCOL_VERSION).toBe("0.9");
	});

	it("names every component with an identifier a freezer accepts", () => {
		for (const [name] of entries) {
			expect(name, `${name} is not an ASCII identifier`).toMatch(IDENTIFIER);
			expect(name).not.toBe(RESERVED_COMPONENT);
		}
	});

	it("gives every component the discriminator its key dispatches on", () => {
		for (const [name, entry] of entries) {
			expect(propertiesOf(entry).component).toEqual({ const: name });
			expect(entry.required).toContain("component");
		}
	});

	it("dispatches anyComponent over exactly the components it publishes", () => {
		const anyComponent = DASHBOARD_CATALOG.$defs.anyComponent;
		expect(anyComponent.discriminator).toEqual({ propertyName: "component" });
		expect(anyComponent.oneOf.map((member) => member.$ref)).toEqual(
			entries.map(([name]) => `#/components/${name}`),
		);
	});

	it("declares every non-discriminator property through a canonical reference", () => {
		// A validator finds a child link and a bindable property by the exact
		// `$ref`; a child declared as `{"type": "string"}` is read as static
		// text, which is the silent failure this refuses.
		for (const [name, entry] of entries) {
			for (const [property, schema] of Object.entries(propertiesOf(entry))) {
				if (property === "component") continue;
				expect(
					schema.$ref,
					`${name}.${property} is not a common_types reference`,
				).toMatch(
					/^common_types\.json#\/\$defs\/(ComponentId|ChildList|Dynamic\w+)$/,
				);
			}
		}
	});

	it("closes no component against the envelope's own fields", () => {
		// `ComponentCommon` (`id`, `catalogId`, `accessibility`) is composed
		// beside a catalog entry with `allOf`, and `additionalProperties` sees
		// only its own schema's properties — so closing an entry would reject
		// the envelope's `id`.
		for (const [name, entry] of entries) {
			expect(entry, `${name} is closed`).not.toHaveProperty(
				"additionalProperties",
			);
		}
	});

	it("names the data model its bindings resolve against", () => {
		expect(DASHBOARD_CATALOG.instructions).toContain(DASHBOARD_DATA_SCHEMA_ID);
		expect(DASHBOARD_DATA_SCHEMA.$id).toBe(DASHBOARD_DATA_SCHEMA_ID);
	});

	it("carries no numbers: no component or data-model property holds a value", () => {
		// The catalog describes series; it never ships one. A `default`,
		// `const` (other than the discriminator) or `examples` keyword would be
		// data in a vocabulary document.
		const document = JSON.stringify(DASHBOARD_CATALOG);
		expect(document).not.toContain('"examples"');
		expect(document).not.toContain('"default"');
		expect(JSON.stringify(DASHBOARD_DATA_SCHEMA)).not.toContain('"examples"');
	});
});

describe("the catalog and WidgetVisualization cannot drift", () => {
	// A deliberate second witness to the five names: `catalog.ts` is checked
	// against the union by the compiler, and this list is checked against the
	// document, so a renamed member fails here even though both halves of the
	// kit moved together. Identity, not count — a list of the same length is
	// not the same list.
	const PUBLISHED: WidgetVisualization[] = [
		"line",
		"bar",
		"area",
		"number",
		"table",
	];

	it("publishes exactly the kit's visualizations", () => {
		expect([...DASHBOARD_VISUALIZATIONS].sort()).toEqual([...PUBLISHED].sort());
	});

	it("puts every visualization in the data model's enum", () => {
		const widget = DASHBOARD_DATA_SCHEMA.$defs.DashboardWidgetView;
		expect(widget.properties.visualization.enum).toEqual(
			DASHBOARD_VISUALIZATIONS,
		);
	});

	it("maps every visualization onto a component the catalog names, or declares the gap", () => {
		for (const visualization of DASHBOARD_VISUALIZATIONS) {
			const component =
				DASHBOARD_WIDGET_COMPONENT_BY_VISUALIZATION[visualization];
			if (component === null) continue;
			expect(
				components,
				`${visualization} maps to ${component}, which the catalog does not publish`,
			).toHaveProperty(component);
		}
	});

	it("declares `table` as the one visualization with no standalone component", () => {
		// Drawn by `<Dashboard>`'s own table body, so there is nothing to name.
		// Pinned so that extracting a table chart, or adding a visualization and
		// forgetting its component, both show up here.
		const canvasOnly = DASHBOARD_VISUALIZATIONS.filter(
			(visualization) =>
				DASHBOARD_WIDGET_COMPONENT_BY_VISUALIZATION[visualization] === null,
		);
		expect(canvasOnly).toEqual(["table"]);
	});

	it("tells a composer which component draws which visualization", () => {
		for (const visualization of DASHBOARD_VISUALIZATIONS) {
			expect(DASHBOARD_CATALOG.instructions).toContain(`\`${visualization}\``);
		}
	});
});

describe("dashboardCatalogComponents", () => {
	it("projects the names a freezer records", () => {
		expect(dashboardCatalogComponents().map((entry) => entry.name)).toEqual(
			entries.map(([name]) => name),
		);
	});

	it("reports the child-bearing property of the container, and no other", () => {
		const projected = dashboardCatalogComponents();
		const withChildren = projected.filter((entry) => entry.children);
		expect(withChildren).toEqual([
			{ name: DASHBOARD_GRID_COMPONENT, children: ["widgets"] },
		]);
		// The whole-canvas component binds its widgets through the data model, so
		// a structural check must not follow anything on it.
		expect(
			projected.find((entry) => entry.name === DASHBOARD_COMPONENT)?.children,
		).toBeUndefined();
	});
});

// A minimal JSON Schema evaluator: `$ref` to a local `$defs`, `type`, `enum`,
// `properties`, `required`, `items`. Enough for the document this kit publishes,
// and written here rather than pulled in as a dependency because the kit ships
// none. Its own refusals are exercised below — an evaluator that accepts
// everything would make the next test pass while proving nothing.
function validate(
	schema: JsonSchemaNode,
	value: unknown,
	path = "",
): string[] {
	const ref = schema.$ref;
	if (typeof ref === "string") {
		const name = ref.replace("#/$defs/", "");
		const target = (
			DASHBOARD_DATA_SCHEMA.$defs as unknown as Record<string, JsonSchemaNode>
		)[name];
		if (!target) return [`${path}: unresolved $ref ${ref}`];
		return validate(target, value, path);
	}
	const errors: string[] = [];
	const types = schema.type
		? Array.isArray(schema.type)
			? (schema.type as string[])
			: [schema.type as string]
		: [];
	if (types.length > 0) {
		const actual =
			value === null
				? "null"
				: Array.isArray(value)
					? "array"
					: typeof value === "number" && Number.isInteger(value)
						? "integer"
						: typeof value;
		const matches = types.some(
			(type) =>
				type === actual ||
				(type === "number" && actual === "integer") ||
				(type === "object" && actual === "object" && !Array.isArray(value)),
		);
		if (!matches) errors.push(`${path}: expected ${types.join("|")}, got ${actual}`);
	}
	if (Array.isArray(schema.enum) && !schema.enum.includes(value as never)) {
		errors.push(`${path}: ${JSON.stringify(value)} is not one of the enum`);
	}
	if (Array.isArray(schema.required) && typeof value === "object" && value !== null) {
		for (const key of schema.required as string[]) {
			if (!(key in (value as Record<string, unknown>))) {
				errors.push(`${path}: missing required ${key}`);
			}
		}
	}
	if (schema.properties && typeof value === "object" && value !== null && !Array.isArray(value)) {
		const properties = schema.properties as Record<string, JsonSchemaNode>;
		for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
			const property = properties[key];
			if (!property) {
				errors.push(`${path}: ${key} is not a declared property`);
				continue;
			}
			if (child === undefined) continue;
			errors.push(...validate(property, child, `${path}/${key}`));
		}
	}
	if (schema.items && Array.isArray(value)) {
		value.forEach((item, index) => {
			errors.push(
				...validate(schema.items as JsonSchemaNode, item, `${path}/${index}`),
			);
		});
	}
	return errors;
}

describe("the kit's own view model validates against the data model it publishes", () => {
	const view = fromDashboardData(
		{
			title: "Activity",
			layout: "grid",
			widgets: [
				{
					id: "trend",
					visualization: "line",
					title: "Sign-ins over time",
					series: {
						points: [{ key: "2026-01-01", value: 3 }],
						total: 3,
						coverage: "complete",
					},
				},
				{
					id: "scalar",
					visualization: "number",
					series: { points: [{ key: "all", value: 7 }], total: 7 },
				},
			],
		},
		{ description: "from a data graph", columns: 3, accent: "#7c3aed" },
	);

	it("accepts the output of fromDashboardData", () => {
		expect(validate(DASHBOARD_DATA_SCHEMA, view)).toEqual([]);
	});

	it("accepts a view of every visualization, including the canvas-only one", () => {
		const everything: DashboardView = {
			widgets: DASHBOARD_VISUALIZATIONS.map((visualization) => ({
				id: visualization,
				visualization,
				series: { points: [], total: null },
				span: 2,
			})),
			layout: "stack",
		};
		expect(validate(DASHBOARD_DATA_SCHEMA, everything)).toEqual([]);
	});

	// Each refusal is mutated from the accepted view above, so a passing
	// evaluation is evidence and not an artefact of a schema that constrains
	// nothing.
	it("refuses a visualization the kit cannot draw", () => {
		const unknown = {
			...view,
			widgets: [{ ...view.widgets[0], visualization: "pie" }],
		};
		expect(validate(DASHBOARD_DATA_SCHEMA, unknown).join("; ")).toContain(
			"is not one of the enum",
		);
	});

	it("refuses a dashboard with no widgets array", () => {
		const withoutWidgets: Record<string, unknown> = { ...view };
		delete withoutWidgets.widgets;
		expect(validate(DASHBOARD_DATA_SCHEMA, withoutWidgets).join("; ")).toContain(
			"missing required widgets",
		);
	});

	it("refuses a point whose value is not a number", () => {
		const text = {
			...view,
			widgets: [
				{
					...view.widgets[0],
					series: { points: [{ key: "a", value: "3" }], total: null },
				},
			],
		};
		expect(validate(DASHBOARD_DATA_SCHEMA, text).join("; ")).toContain(
			"expected number, got string",
		);
	});

	it("refuses a total of zero written where unavailable was meant to be null", () => {
		// `total: null` is legal and `total: 3` is legal; a string total is not,
		// which is what keeps "unavailable" a value rather than a spelling.
		const bad = {
			...view,
			widgets: [
				{
					...view.widgets[0],
					series: { points: [], total: "unavailable" },
				},
			],
		};
		expect(validate(DASHBOARD_DATA_SCHEMA, bad).join("; ")).toContain(
			"expected number|null, got string",
		);
	});

	it("refuses a widget property the view model does not have", () => {
		const extra = {
			...view,
			widgets: [{ ...view.widgets[0], pieSlices: 4 }],
		};
		expect(validate(DASHBOARD_DATA_SCHEMA, extra).join("; ")).toContain(
			"pieSlices is not a declared property",
		);
	});
});
