import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";

import { generatedPinsErrors, parsePins } from "./generated-pins-gate.mjs";

const TEMPLATE = `version: v2
clean: true
managed:
  enabled: true
plugins:
  - local: [go, run, google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11]
    out: code/pkg/gen
    opt: paths=source_relative
  - local: [go, run, google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.6.1]
    out: code/pkg/gen
    opt: paths=source_relative
  - local: [go, run, github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.29.0]
    out: code/pkg/gen
    opt: paths=source_relative
  - local: [npx, --prefix, ../frontend/code, --no-install, protoc-gen-es]
    out: ../frontend/code/src/gen
`;

// The goimports-grouped import block the generation pipeline produces: stdlib
// (and non-dotted local paths) first, blank line, then third-party.
const GOIMPORTS_BODY = `
package accountsv1

import (
	_ "accounts/pkg/gen/saas/policy/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)
`;

// What raw \`buf generate\` emits: one gofmt-sorted block, so the stdlib imports
// land last. This is the exact shape #528 committed.
const RAW_BODY = `
package accountsv1

import (
	_ "accounts/pkg/gen/saas/policy/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)
`;

const goStamp = (v) => `// Code generated by protoc-gen-go. DO NOT EDIT.\n// versions:\n// \tprotoc-gen-go v${v}\n// \tprotoc        (unknown)\n`;
const grpcStamp = (v) => `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\n// versions:\n// - protoc-gen-go-grpc v${v}\n// - protoc             (unknown)\n`;

// Build a throwaway module tree holding one service with the given template and
// generated files, run the gate against it, and clean up.
function withService(files, body, { template = TEMPLATE, service = "accounts" } = {}) {
  const root = mkdtempSync(join(tmpdir(), "generated-pins-"));
  try {
    const serviceRoot = join(root, "services", service);
    mkdirSync(serviceRoot, { recursive: true });
    if (template !== null) writeFileSync(join(serviceRoot, "buf.gen.local.yaml"), template);
    for (const [rel, source] of Object.entries(files)) {
      const full = join(serviceRoot, rel);
      mkdirSync(dirname(full), { recursive: true });
      writeFileSync(full, source);
    }
    return body(root);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

test("the shipped generated tree satisfies the gate", () => {
  assert.deepEqual(generatedPinsErrors(join(import.meta.dirname, "..")), []);
});

test("output from the pinned plugins in pipeline shape passes", () => {
  withService(
    {
      "code/pkg/gen/saas/accounts/v1/identity.pb.go": goStamp("1.36.11") + GOIMPORTS_BODY,
      "code/pkg/gen/saas/accounts/v1/identity_grpc.pb.go": grpcStamp("1.6.1") + GOIMPORTS_BODY,
    },
    (root) => assert.deepEqual(generatedPinsErrors(root), []),
  );
});

// The #527 defect: regenerated with ambient workstation plugins newer than the
// pins, landing files no pinned run reproduces. This blocked every open PR.
test("a protoc-gen-go stamp newer than the pin is caught", () => {
  withService(
    { "code/pkg/gen/saas/accounts/v1/module_registration.pb.go": goStamp("1.36.12") + GOIMPORTS_BODY },
    (root) => {
      const errors = generatedPinsErrors(root);
      assert.equal(errors.length, 1);
      assert.match(errors[0], /module_registration\.pb\.go: generated by protoc-gen-go v1\.36\.12 but accounts\/buf\.gen\.local\.yaml pins v1\.36\.11/);
    },
  );
});

test("a protoc-gen-go-grpc stamp newer than the pin is caught", () => {
  withService(
    { "code/pkg/gen/saas/accounts/v1/module_capabilities_grpc.pb.go": grpcStamp("1.6.2") + GOIMPORTS_BODY },
    (root) => {
      const errors = generatedPinsErrors(root);
      assert.equal(errors.length, 1);
      assert.match(errors[0], /generated by protoc-gen-go-grpc v1\.6\.2 but accounts\/buf\.gen\.local\.yaml pins v1\.6\.1/);
    },
  );
});

// The #528 defect: correct stamps, but regenerated with `buf generate` directly
// so the goimports pass never ran. Valid gofmt, so no fmt or lint step sees it —
// only the byte-drift gate, which is exactly what this exists to pre-empt.
test("a correctly stamped file in raw plugin shape is still caught", () => {
  withService(
    { "code/pkg/gen/saas/accounts/v1/module_registration.pb.go": goStamp("1.36.11") + RAW_BODY },
    (root) => {
      const errors = generatedPinsErrors(root);
      assert.equal(errors.length, 1);
      assert.match(errors[0], /stdlib imports sort after third-party — raw plugin output, not goimports-grouped/);
    },
  );
});

// The grpc half of the same defect: `context` still sorts first, so only the
// dropped blank line distinguishes raw output from pipeline output.
test("a stdlib group not separated by a blank line is caught", () => {
  const unseparated = `
package accountsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
)
`;
  withService(
    { "code/pkg/gen/saas/accounts/v1/module_capabilities_grpc.pb.go": grpcStamp("1.6.1") + unseparated },
    (root) => {
      const errors = generatedPinsErrors(root);
      assert.equal(errors.length, 1);
      assert.match(errors[0], /no blank line between the stdlib and third-party import groups/);
    },
  );
});

test("both a wrong stamp and a wrong shape are reported together", () => {
  withService(
    { "code/pkg/gen/saas/accounts/v1/module_registration.pb.go": goStamp("1.36.12") + RAW_BODY },
    (root) => assert.equal(generatedPinsErrors(root).length, 2),
  );
});

test("a file with no third-party import is not a shape failure", () => {
  const stdlibOnly = `
package accountsv1

import (
	reflect "reflect"
	sync "sync"
)
`;
  withService(
    { "code/pkg/gen/saas/accounts/v1/common.pb.go": goStamp("1.36.11") + stdlibOnly },
    (root) => assert.deepEqual(generatedPinsErrors(root), []),
  );
});

test("a file with no stdlib import is not a shape failure", () => {
  const thirdPartyOnly = `
package accountsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)
`;
  withService(
    { "code/pkg/gen/saas/accounts/v1/common.pb.go": goStamp("1.36.11") + thirdPartyOnly },
    (root) => assert.deepEqual(generatedPinsErrors(root), []),
  );
});

test("a missing stamp is caught rather than silently passing", () => {
  withService(
    { "code/pkg/gen/saas/accounts/v1/identity.pb.go": "// hand-written\n" + GOIMPORTS_BODY },
    (root) => {
      const errors = generatedPinsErrors(root);
      assert.equal(errors.length, 1);
      assert.match(errors[0], /no protoc-gen-go version stamp; expected v1\.36\.11/);
    },
  );
});

// grpc-gateway and connect-go write no version into their headers, so there is
// nothing to compare and their files must not be mistaken for protoc-gen-go's.
test("gateway and connect output is not claimed by the protoc-gen-go rule", () => {
  withService(
    {
      "code/pkg/gen/saas/accounts/v1/identity.pb.gw.go": "// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.\n" + RAW_BODY,
      "code/pkg/gen/saas/accounts/v1/accountsv1connect/identity.connect.go": "// Code generated by protoc-gen-connect-go. DO NOT EDIT.\n" + RAW_BODY,
    },
    (root) => assert.deepEqual(generatedPinsErrors(root), []),
  );
});

test("a service shipping no buf.gen.local.yaml is skipped", () => {
  withService(
    { "code/pkg/gen/saas/accounts/v1/identity.pb.go": goStamp("9.9.9") + RAW_BODY },
    (root) => assert.deepEqual(generatedPinsErrors(root), []),
    { template: null },
  );
});

test("each service is checked against its own pins", () => {
  const root = mkdtempSync(join(tmpdir(), "generated-pins-multi-"));
  try {
    for (const service of ["accounts", "auth-gateway"]) {
      const dir = join(root, "services", service, "code/pkg/gen/saas/accounts/v1");
      mkdirSync(dir, { recursive: true });
      writeFileSync(join(root, "services", service, "buf.gen.local.yaml"), TEMPLATE);
      const version = service === "auth-gateway" ? "1.36.12" : "1.36.11";
      writeFileSync(join(dir, "module_registration.pb.go"), goStamp(version) + GOIMPORTS_BODY);
    }
    const errors = generatedPinsErrors(root);
    assert.equal(errors.length, 1);
    assert.match(errors[0], /auth-gateway\/buf\.gen\.local\.yaml pins v1\.36\.11/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("parsePins reads each pinned plugin with its out directory", () => {
  const pins = parsePins(TEMPLATE);
  assert.deepEqual(pins.get("protoc-gen-go"), { version: "v1.36.11", out: "code/pkg/gen" });
  assert.deepEqual(pins.get("protoc-gen-go-grpc"), { version: "v1.6.1", out: "code/pkg/gen" });
  assert.deepEqual(pins.get("protoc-gen-grpc-gateway"), { version: "v2.29.0", out: "code/pkg/gen" });
});

test("parsePins ignores an unpinned plugin", () => {
  // proto/buf.gen.yaml invokes bare binaries with no version to compare.
  const pins = parsePins("plugins:\n  - local: protoc-gen-go\n    out: ../code/pkg/gen\n");
  assert.equal(pins.size, 0);
  // The lockfile-pinned TypeScript plugin carries no @version either.
  assert.equal(parsePins(TEMPLATE).has("protoc-gen-es"), false);
});

test("parsePins stops at the end of the plugins block", () => {
  const trailing = TEMPLATE + "inputs:\n  - directory: proto\n";
  assert.equal(parsePins(trailing).size, 3);
});
