package infra_test

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

var updateControlPlaneCallSites = flag.Bool("update", false, "rewrite testdata/control_plane_call_sites.txt with the call sites the tree has now")

const controlPlaneCallSitesGolden = "testdata/control_plane_call_sites.txt"

// TestControlPlaneCallSites is the static half of the control-plane audit whose
// runtime half is ControlPlaneCounters. It lists every place outside tests, in
// the whole accounts module, that reaches cross-tenant authority — a
// WithControlPlane or withControlPlaneTx reference, a business.System()
// identity (As(System()), on its own, or taken as a function value), a System
// identity built without naming System (Identity's system field set in a
// literal, positionally, by assignment or through its address, anywhere but
// in System itself), any use of the control-plane pool field — or that labels
// a transaction's authority with one of txbind's binders (called or taken as a
// value), each by file and enclosing function, and compares the list with the
// committed one. A new call
// site fails this test until the list is updated, so it is reviewed as a line
// in the diff rather than discovered in production; a removed one fails it too,
// so the list never names a site that no longer exists. A dot-import of
// pkg/business, storetx or txbind anywhere in the module, tests included, fails
// it outright: it turns every selector this walk looks for into a bare name.
//
// Every site is one line, repeated when a function holds several, and line
// numbers are deliberately absent so that unrelated edits do not churn the
// list. Regenerate it, from module/services/accounts/code, with:
//
//	go test -tags=pure ./pkg/infra -run '^TestControlPlaneCallSites$' -update
//
// This is a convention check, not a capability: nothing here stops a reviewed
// call site from doing the wrong thing. Relabelling a transaction is the
// capability, and the compiler holds it: txbind is internal to pkg/infra
// (TestOnlyInfraCanBindAStoreTransaction).
func TestControlPlaneCallSites(t *testing.T) {
	sites := collectControlPlaneCallSites(t, filepath.Clean("../.."))
	require.NotEmpty(t, sites, "the walk found no control-plane call sites at all; it is broken")

	if *updateControlPlaneCallSites {
		header := "# Every non-test control-plane call site in accounts, one per line: file, enclosing function, form.\n" +
			"# Generated by TestControlPlaneCallSites; regenerate with\n" +
			"#   go test -tags=pure ./pkg/infra -run '^TestControlPlaneCallSites$' -update\n"
		require.NoError(t, os.WriteFile(controlPlaneCallSitesGolden, []byte(header+strings.Join(sites, "\n")+"\n"), 0o644))
		return
	}

	raw, err := os.ReadFile(controlPlaneCallSitesGolden)
	require.NoError(t, err)
	var want []string
	for _, line := range strings.Split(string(raw), "\n") {
		if line != "" && !strings.HasPrefix(line, "#") {
			want = append(want, line)
		}
	}
	added, removed := multisetDifference(sites, want), multisetDifference(want, sites)
	if len(added) > 0 || len(removed) > 0 {
		t.Fatalf("control-plane call sites differ from %s; review the change, then regenerate the list:\n"+
			"  go test -tags=pure ./pkg/infra -run '^TestControlPlaneCallSites$' -update\n"+
			"new call sites:\n  %s\ncall sites no longer present:\n  %s",
			controlPlaneCallSitesGolden, strings.Join(added, "\n  "), strings.Join(removed, "\n  "))
	}
}

// TestNoTenantRebindingOutsideInfra fails on a string literal, in a non-test Go
// file outside pkg/infra, that binds or reads a transaction's request scope or
// role: set_config(, SET [LOCAL|SESSION] ROLE, RESET ROLE or app.current_,
// matched without regard to case or spacing. pkg/business, pkg/auth/pg and
// pkg/billing/pg hold the raw transaction through storetx.Tx, and one such
// statement on it would rebind the tenant — or leave app_tenant — under a
// binding that still claims the org, user and role pkg/infra set, which is what
// As(identity).Within trusts when it joins. Binding a transaction is pkg/infra's
// alone (txbind), and so is the SQL that does it.
//
// An UPDATE's SET clause assigning a column named role is not a role change,
// so a SET ROLE match in a statement that began as an UPDATE is not reported.
// A statement split into literals joined with + is matched whole. internal/testdb
// provisions the test logins as the superuser and is exempt, because nothing
// but tests imports it — which this test also checks.
//
// Like TestControlPlaneCallSites this is a convention check, not a capability:
// a statement assembled from named constants or at run time is outside what a
// lexical scan can see.
func TestNoTenantRebindingOutsideInfra(t *testing.T) {
	const testdbImport = "accounts/internal/testdb"
	var found []string
	walkModuleGoFiles(t, filepath.Clean("../.."), func(rel string, file *ast.File) error {
		if strings.HasSuffix(rel, "_test.go") {
			return nil
		}
		inTestdb := strings.HasPrefix(rel, "internal/testdb/")
		for _, spec := range file.Imports {
			if path, _ := strconv.Unquote(spec.Path.Value); path == testdbImport && !inTestdb {
				found = append(found, rel+": imports "+testdbImport+", which only tests may: it is exempt from this check")
			}
		}
		if inTestdb || strings.HasPrefix(rel, "pkg/infra/") {
			return nil
		}
		for _, hit := range tenantRebindingIn(file) {
			found = append(found, rel+": "+hit)
		}
		return nil
	})
	require.Empty(t, found, "only pkg/infra may bind a transaction's request scope or role; move the statement behind a pkg/infra method")
}

// The rebinding scan reports each statement form wherever a literal spells it,
// whatever its case, spacing or split across a + chain, and leaves an UPDATE
// assigning a role column alone.
func TestTenantRebindingScanSeesEveryForm(t *testing.T) {
	file, err := parser.ParseFile(token.NewFileSet(), "synthetic.go", `package business

const bindOrg = "SELECT set_config('app.current_org_id', $1, true)"

func escalate(ctx context.Context, tx pgx.Tx) {
	_, _ = tx.Exec(ctx, "SET ROLE app_control_plane")
	_, _ = tx.Exec(ctx, `+"`"+`set  local
		role app_control_plane`+"`"+`)
	_, _ = tx.Exec(ctx, "SET SESSION ROLE app_control_plane")
	_, _ = tx.Exec(ctx, "reset role")
	_, _ = tx.Exec(ctx, "SELECT pg_catalog.set_config ('role', 'app_control_plane', true)")
	_, _ = tx.Exec(ctx, "SELECT current_setting('app.current_user_id', true)")
	_, _ = tx.Exec(ctx, "SET LOCAL " + "ROLE " + role)
	_, _ = tx.Exec(ctx, "UPDATE organization_members SET a = 1; SET role = 'app_control_plane'")
}

func harmless(ctx context.Context, tx pgx.Tx) {
	_, _ = tx.Exec(ctx, "UPDATE organization_members SET role = $1 WHERE user_id = $2")
	_, _ = tx.Exec(ctx, `+"`"+`INSERT INTO organization_members (org_id, user_id, role) VALUES ($1, $2, $3)
		ON CONFLICT (org_id, user_id) DO UPDATE SET role = $3`+"`"+`)
	_, _ = tx.Exec(ctx, "SELECT role FROM organization_members WHERE user_id = $1")
	_, _ = tx.Exec(ctx, "SET " + role)
	// SET ROLE app_control_plane in a comment is not a statement.
}`, parser.SkipObjectResolution)
	require.NoError(t, err)
	var got []string
	for _, hit := range tenantRebindingIn(file) {
		got = append(got, hit[:strings.Index(hit, " in ")])
	}
	require.ElementsMatch(t, []string{
		"(package level): set_config(",
		"(package level): app.current_",
		"escalate: SET ROLE",
		"escalate: SET ROLE",
		"escalate: SET ROLE",
		"escalate: RESET ROLE",
		"escalate: set_config(",
		"escalate: app.current_",
		"escalate: SET ROLE",
		"escalate: SET ROLE",
	}, got)
}

// tenantRebinding are the statements that bind a transaction's request scope or
// role, or read the scope back.
var tenantRebinding = []struct {
	name    string
	pattern *regexp.Regexp
}{
	{"set_config(", regexp.MustCompile(`(?i)\bset_config\s*\(`)},
	{"SET ROLE", regexp.MustCompile(`(?i)\bSET\s+(?:LOCAL\s+|SESSION\s+)?ROLE\b`)},
	{"RESET ROLE", regexp.MustCompile(`(?i)\bRESET\s+ROLE\b`)},
	{"app.current_", regexp.MustCompile(`(?i)\bapp\s*\.\s*current_`)},
}

var updateStatement = regexp.MustCompile(`(?i)\bUPDATE\b`)

// tenantRebindingIn returns "function: pattern in <literal>" for every string
// literal in file, or chain of literals joined with +, that matches one of
// tenantRebinding.
func tenantRebindingIn(file *ast.File) []string {
	var hits []string
	for _, decl := range file.Decls {
		function := "(package level)"
		if fn, ok := decl.(*ast.FuncDecl); ok {
			function = funcDeclName(fn)
		}
		// Literals already matched as part of a + chain, and the inner + of a
		// chain already matched from its outermost one.
		seen := map[ast.Node]bool{}
		check := func(text string) {
			shown := text
			if len(shown) > 80 {
				shown = shown[:80] + "…"
			}
			for _, rule := range tenantRebinding {
				for _, match := range rule.pattern.FindAllStringIndex(text, -1) {
					statement := text[strings.LastIndex(text[:match[0]], ";")+1 : match[0]]
					if rule.name == "SET ROLE" && updateStatement.MatchString(statement) {
						continue
					}
					hits = append(hits, fmt.Sprintf("%s: %s in %q", function, rule.name, shown))
					break
				}
			}
		}
		ast.Inspect(decl, func(node ast.Node) bool {
			switch n := node.(type) {
			case *ast.BinaryExpr:
				if n.Op != token.ADD || seen[n] {
					return true
				}
				var text strings.Builder
				literal := false
				var flatten func(ast.Expr)
				flatten = func(expr ast.Expr) {
					switch e := expr.(type) {
					case *ast.ParenExpr:
						flatten(e.X)
						return
					case *ast.BinaryExpr:
						if e.Op == token.ADD {
							seen[e] = true
							flatten(e.X)
							flatten(e.Y)
							return
						}
					case *ast.BasicLit:
						if value, err := strconv.Unquote(e.Value); err == nil && e.Kind == token.STRING {
							seen[e] = true
							literal = true
							text.WriteString(value)
							return
						}
					}
					// A value only known at run time: nothing matches across it.
					text.WriteString("\x00")
				}
				flatten(n)
				if literal {
					check(text.String())
				}
			case *ast.BasicLit:
				if n.Kind != token.STRING || seen[n] {
					return true
				}
				if value, err := strconv.Unquote(n.Value); err == nil {
					check(value)
				}
			}
			return true
		})
	}
	return hits
}

// multisetDifference returns the lines of a not matched one-for-one by b.
func multisetDifference(a, b []string) []string {
	remaining := map[string]int{}
	for _, line := range b {
		remaining[line]++
	}
	var out []string
	for _, line := range a {
		if remaining[line] > 0 {
			remaining[line]--
			continue
		}
		out = append(out, line)
	}
	return out
}

// collectControlPlaneCallSites parses every non-generated Go file under root and
// returns one sorted "file: function: form" line per site in a non-test file. It
// fails on a dot-import of the packages it looks for in any file, test files
// included.
func collectControlPlaneCallSites(t *testing.T, root string) []string {
	t.Helper()
	var sites []string
	walkModuleGoFiles(t, root, func(rel string, file *ast.File) error {
		found, err := controlPlaneSitesIn(file)
		if err != nil {
			return fmt.Errorf("%s: %w", rel, err)
		}
		if strings.HasSuffix(rel, "_test.go") {
			return nil
		}
		for _, site := range found {
			sites = append(sites, rel+": "+site)
		}
		return nil
	})
	slices.Sort(sites)
	return sites
}

// walkModuleGoFiles parses every non-generated Go file under root, tests
// included, and hands each to visit with its slash-separated path relative to
// root.
func walkModuleGoFiles(t *testing.T, root string, visit func(rel string, file *ast.File) error) {
	t.Helper()
	fset := token.NewFileSet()
	require.NoError(t, filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if d.IsDir() {
			if rel != "." && (strings.HasPrefix(d.Name(), ".") || d.Name() == "testdata" || d.Name() == "node_modules" || rel == "pkg/gen") {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		file, err := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
		if err != nil {
			return err
		}
		return visit(rel, file)
	}))
}

const (
	businessImport = "accounts/pkg/business"
	storetxImport  = "accounts/pkg/infra/storetx"
	txbindImport   = "accounts/pkg/infra/internal/txbind"
)

// controlPlaneSitesIn returns "function: form" for every site in one file, and
// an error when the file dot-imports a package the walk looks for: the walk
// finds a site by the selector naming it, and a dot-import leaves a bare name
// that a local identifier could equally be.
func controlPlaneSitesIn(file *ast.File) ([]string, error) {
	businessName, txbindName := "", ""
	for _, spec := range file.Imports {
		path, _ := strconv.Unquote(spec.Path.Value)
		name := filepath.Base(path)
		if spec.Name != nil {
			name = spec.Name.Name
		}
		switch path {
		case businessImport, storetxImport, txbindImport:
			if name == "." {
				return nil, fmt.Errorf("dot-import of %s hides its control-plane call sites from TestControlPlaneCallSites; import it by name", path)
			}
		}
		switch path {
		case businessImport:
			businessName = name
		case txbindImport:
			txbindName = name
		}
	}
	// isSystem reports whether expr names business.System, called or not.
	isSystem := func(expr ast.Expr) bool {
		switch fun := expr.(type) {
		case *ast.Ident:
			return file.Name.Name == "business" && fun.Name == "System"
		case *ast.SelectorExpr:
			return businessName != "" && isIdent(fun.X, businessName) && fun.Sel.Name == "System"
		}
		return false
	}
	isSystemCall := func(expr ast.Expr) bool {
		call, ok := expr.(*ast.CallExpr)
		return ok && len(call.Args) == 0 && isSystem(call.Fun)
	}
	// binder returns the name of the txbind binder expr names, called or not.
	binder := func(expr ast.Expr) (string, bool) {
		sel, ok := expr.(*ast.SelectorExpr)
		if !ok || txbindName == "" || !isIdent(sel.X, txbindName) || !strings.HasPrefix(sel.Sel.Name, "Bind") {
			return "", false
		}
		return sel.Sel.Name, true
	}
	isControlPlaneField := func(expr ast.Expr) bool {
		sel, ok := expr.(*ast.SelectorExpr)
		return ok && sel.Sel.Name == "controlPlane"
	}
	// isIdentity reports whether expr spells business.Identity, or a pointer to
	// it.
	isIdentity := func(expr ast.Expr) bool {
		if star, ok := expr.(*ast.StarExpr); ok {
			expr = star.X
		}
		switch typ := expr.(type) {
		case *ast.Ident:
			return file.Name.Name == "business" && typ.Name == "Identity"
		case *ast.SelectorExpr:
			return businessName != "" && isIdent(typ.X, businessName) && typ.Sel.Name == "Identity"
		}
		return false
	}
	isSystemField := func(expr ast.Expr) bool {
		sel, ok := expr.(*ast.SelectorExpr)
		return ok && sel.Sel.Name == "system"
	}

	var sites []string
	for _, decl := range file.Decls {
		function := "(package level)"
		consumed := map[ast.Node]bool{}
		// System itself is the one place a System identity is meant to be built.
		buildsSystem := false
		if fn, ok := decl.(*ast.FuncDecl); ok {
			function = funcDeclName(fn)
			// A declaration's own name is not a use of it.
			consumed[fn.Name] = true
			buildsSystem = file.Name.Name == "business" && fn.Recv == nil && fn.Name.Name == "System"
		}
		// elided holds the element type of a composite literal whose type is
		// left out, such as each element of []Identity{{...}}, taken from the
		// literal around it.
		elided := map[*ast.CompositeLit]ast.Expr{}
		record := func(form string) { sites = append(sites, function+": "+form) }
		ast.Inspect(decl, func(node ast.Node) bool {
			// A consumed node was already recorded as part of its parent's form.
			if node == nil || consumed[node] {
				return false
			}
			switch n := node.(type) {
			case *ast.CallExpr:
				fun, isSelector := n.Fun.(*ast.SelectorExpr)
				name, isBinder := binder(n.Fun)
				switch {
				case isSelector && fun.Sel.Name == "As" && len(n.Args) == 1 && isSystemCall(n.Args[0]):
					record("As(System())")
					consumed[n.Args[0]] = true
				case isBinder:
					record("txbind." + name)
					consumed[n.Fun] = true
				case isSelector && isControlPlaneField(fun.X):
					record("controlPlane." + fun.Sel.Name)
					consumed[fun.X] = true
				case isSystemCall(n):
					record("System()")
					consumed[n.Fun] = true
				default:
					for _, arg := range n.Args {
						if isControlPlaneField(arg) {
							record(exprName(n.Fun) + "(controlPlane)")
							consumed[arg] = true
						}
					}
				}
			case *ast.SelectorExpr:
				// The selected name is part of this selector, never a bare use.
				consumed[n.Sel] = true
				name, isBinder := binder(n)
				switch {
				case n.Sel.Name == "WithControlPlane", n.Sel.Name == "withControlPlaneTx":
					record(n.Sel.Name)
				case n.Sel.Name == "controlPlane":
					record("controlPlane")
				case isSystem(n):
					// Not called here: a function value that yields System() later,
					// under whatever name it is stored as.
					record("System (value)")
				case isBinder:
					record("txbind." + name + " (value)")
				}
			case *ast.Ident:
				if isSystem(n) {
					record("System (value)")
				}
			case *ast.CompositeLit:
				typ := n.Type
				if typ == nil {
					typ = elided[n]
				}
				// Hand an element type down to the elements that leave it out.
				var element ast.Expr
				switch container := typ.(type) {
				case *ast.ArrayType:
					element = container.Elt
				case *ast.MapType:
					element = container.Value
				}
				for _, elt := range n.Elts {
					if kv, ok := elt.(*ast.KeyValueExpr); ok {
						elt = kv.Value
					}
					if unary, ok := elt.(*ast.UnaryExpr); ok && unary.Op == token.AND {
						elt = unary.X
					}
					if lit, ok := elt.(*ast.CompositeLit); ok && lit.Type == nil && element != nil {
						elided[lit] = element
					}
				}
				if buildsSystem {
					break
				}
				// A struct literal keyed system: Identity is the only struct in
				// the module with that field, so this holds whatever the literal's
				// type is spelled as — Identity, an alias of it, a type defined
				// over it, or an element type left out. The keys of a map, slice or
				// array literal are values, not fields.
				switch typ.(type) {
				case *ast.MapType, *ast.ArrayType:
				default:
					for _, elt := range n.Elts {
						if kv, ok := elt.(*ast.KeyValueExpr); ok && isIdent(kv.Key, "system") {
							record("Identity{system: …}")
						}
					}
				}
				if isIdentity(typ) && len(n.Elts) > 0 {
					if _, keyed := n.Elts[0].(*ast.KeyValueExpr); !keyed {
						record("Identity{…} (positional)")
					}
				}
			case *ast.AssignStmt:
				for _, lhs := range n.Lhs {
					if isSystemField(lhs) && !buildsSystem {
						record(".system = …")
					}
				}
			case *ast.UnaryExpr:
				if n.Op == token.AND && isSystemField(n.X) && !buildsSystem {
					record("&.system")
				}
			}
			return true
		})
	}
	return sites, nil
}

func isIdent(expr ast.Expr, name string) bool {
	ident, ok := expr.(*ast.Ident)
	return ok && ident.Name == name
}

// exprName renders an identifier or selector chain, such as pgx.BeginTxFunc or
// storetx.ControlPlane, and "?" for anything else.
func exprName(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return exprName(e.X) + "." + e.Sel.Name
	}
	return "?"
}

// funcDeclName names a function "Name" and a method "(*Recv).Name" or
// "(Recv).Name".
func funcDeclName(fn *ast.FuncDecl) string {
	if fn.Recv == nil || len(fn.Recv.List) == 0 {
		return fn.Name.Name
	}
	var recv func(ast.Expr) string
	recv = func(expr ast.Expr) string {
		switch e := expr.(type) {
		case *ast.StarExpr:
			return "*" + recv(e.X)
		case *ast.Ident:
			return e.Name
		case *ast.IndexExpr:
			return recv(e.X)
		case *ast.IndexListExpr:
			return recv(e.X)
		}
		return fmt.Sprintf("%T", expr)
	}
	return "(" + recv(fn.Recv.List[0].Type) + ")." + fn.Name.Name
}
