// Code generated by module-compose. DO NOT EDIT.
package permissioncatalog

type Permission struct {
	Name     string
	Resource string
	Action   string
	// Members is true when every organization member holds it.
	Members bool
}

var permissions = [...]Permission{}

func Permissions() []Permission {
	return append([]Permission(nil), permissions[:]...)
}
