// Code generated by module-compose. DO NOT EDIT.
package permissioncatalog

type Permission struct {
	Name     string
	Resource string
	Action   string
}

var permissions = [...]Permission{}

func Permissions() []Permission {
	return append([]Permission(nil), permissions[:]...)
}
