// Code generated by codefly agent. DO NOT EDIT.
package plugins

import "backend/pkg/framework"

// All returns the list of registered plugins.
// This file is regenerated from plugins.yaml by the codefly agent during Sync.
func All() []framework.Plugin {
	return nil
}
