// Code generated by module-compose. DO NOT EDIT.
package eventcatalog

type PublishedEvent struct {
	Type       string
	Namespace  string
	Schema     string
	Major      int
	Visibility string
	Partition  string
	Retention  string
}

type ConsumedEvent struct {
	Type       string
	Subscriber string
	Queue      string
	Delivery   string
}

var published = [...]PublishedEvent{
	{Type: "installation.created", Namespace: "installation", Schema: "saas/events/v1/events.proto#EventEnvelope", Major: 1, Visibility: "internal", Partition: "{tenant_id}", Retention: "30d"},
	{Type: "installation.revoked", Namespace: "installation", Schema: "saas/events/v1/events.proto#EventEnvelope", Major: 1, Visibility: "internal", Partition: "{tenant_id}", Retention: "30d"},
	{Type: "reference.console.viewed", Namespace: "reference", Schema: "saas/events/v1/events.proto#EventEnvelope", Major: 1, Visibility: "tenant", Partition: "{tenant_id}", Retention: "30d"},
	{Type: "scope.granted", Namespace: "scope", Schema: "saas/events/v1/events.proto#EventEnvelope", Major: 1, Visibility: "tenant", Partition: "{tenant_id}", Retention: "30d"},
	{Type: "scope.revoked", Namespace: "scope", Schema: "saas/events/v1/events.proto#EventEnvelope", Major: 1, Visibility: "tenant", Partition: "{tenant_id}", Retention: "30d"},
}

var consumed = [...]ConsumedEvent{
	{Type: "reference.console.viewed", Subscriber: "reference", Queue: "reference.ingest", Delivery: "unordered"},
}

func Published() []PublishedEvent {
	return append([]PublishedEvent(nil), published[:]...)
}

func Consumed() []ConsumedEvent {
	return append([]ConsumedEvent(nil), consumed[:]...)
}
