// Code generated by module-compose. DO NOT EDIT.
package eventcatalog

type PublishedEvent struct {
	Type       string
	Namespace  string
	Schema     string
	Major      int
	Visibility string
	Partition  string
	Retention  string
}

type ConsumedEvent struct {
	Type       string
	Subscriber string
	Queue      string
	Delivery   string
}

var published = [...]PublishedEvent{}

var consumed = [...]ConsumedEvent{}

func Published() []PublishedEvent {
	return append([]PublishedEvent(nil), published[:]...)
}

func Consumed() []ConsumedEvent {
	return append([]ConsumedEvent(nil), consumed[:]...)
}
