package main

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

Recommendation: write your logic in the `work.go` file in the same directory.


// Register the work function

func init() {
	WithWork(doWork)
}

func doWork(ctx context.Context) (Clean, error) {
	// Your logic goes here
}

----------------------------------------------------------------- */

import (
	"accounts/pkg/adapters"
	"context"
	"fmt"
	"os/signal"
	"syscall"

	"github.com/codefly-dev/core/shared"
	"github.com/codefly-dev/core/standards"

	codefly "github.com/codefly-dev/sdk-go"
)

type Clean func()
type Work func(ctx context.Context) (Clean, error)

var work Work

func WithWork(w Work) {
	work = w
}

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	provider, err := codefly.Init(ctx)
	if err != nil {
		panic(err)
	}
	ctx = provider.Inject(ctx)

	defer codefly.CatchPanic(ctx)

	config := &adapters.Configuration{
		EndpointGrpcPort: codefly.For(ctx).WithDefaultNetwork().API(standards.GRPC).NetworkInstance().Port,
	}
	if net := codefly.For(ctx).WithDefaultNetwork().API(standards.REST).NetworkInstance(); net != nil {
		config.EndpointHttpPort = shared.Pointer(net.Port)
	}
	if net := codefly.For(ctx).WithDefaultNetwork().API(standards.CONNECT).NetworkInstance(); net != nil {
		config.EndpointConnectPort = shared.Pointer(net.Port)
	}

	// Complete dependency wiring, plugin registration and fixture seeding before
	// opening any listener. Starting the generated server first exposes handlers
	// while the package-level business service is still nil and makes a passing
	// port probe race with application readiness.
	if work != nil {
		clean, err := work(ctx)
		if err != nil {
			panic(err)
		}
		if clean != nil {
			defer clean()
		}
	}

	server, err := adapters.NewServer(config)
	if err != nil {
		panic(err)
	}

	go func() {
		if startErr := server.Start(context.Background()); startErr != nil {
			panic(startErr)
		}
	}()

	<-ctx.Done()
	server.Stop()
	fmt.Println("got interruption signal")

}
