package main

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

Recommendation: write your logic in the `work.go` file in the same directory.


// Register the work function

func init() {
	WithWork(doWork)
}

func doWork(ctx context.Context) (Clean, error) {
	// Your logic goes here
}

----------------------------------------------------------------- */

import (
	"accounts/pkg/adapters"
	"accounts/pkg/business"
	"context"
	"fmt"
	"os/signal"
	"syscall"

	"github.com/codefly-dev/core/shared"
	"github.com/codefly-dev/core/standards"
	"github.com/codefly-dev/core/wool"

	codefly "github.com/codefly-dev/sdk-go"
)

// resolvedPort is the port of one of this service's own endpoints, or nil when
// it does not resolve. A nil port serves no listener for the endpoint and says
// so loudly; it does not substitute a default one.
func resolvedPort(ctx context.Context, api string) *uint16 {
	instance, err := codefly.For(ctx).API(api).ResolveNetworkInstance()
	if err != nil {
		wool.Get(ctx).In("main").Error(
			"the endpoint did not resolve; no listener is served for it",
			wool.Field("endpoint", api),
			wool.ErrField(err),
		)
		return nil
	}
	return shared.Pointer(instance.Port)
}

type Clean func()
type Work func(ctx context.Context) (Clean, error)

var work Work

func WithWork(w Work) {
	work = w
}

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	provider, err := codefly.Init(ctx)
	if err != nil {
		panic(err)
	}
	ctx = provider.Inject(ctx)

	defer codefly.CatchPanic(ctx)

	// The SDK resolves an endpoint from the carrier the runtime injected or, in a
	// local run, from the workspace's endpoint map, and never invents a port: an
	// address that does not resolve is an error here, not a default.
	//
	// gRPC is what this process is. Without it there is nothing to start.
	grpcNet, grpcErr := codefly.For(ctx).API(standards.GRPC).ResolveNetworkInstance()
	if grpcErr != nil || grpcNet == nil {
		panic(fmt.Sprintf("Codefly gRPC endpoint is unavailable: %v", grpcErr))
	}
	config := &adapters.Configuration{
		EndpointGrpcPort:    grpcNet.Port,
		EndpointHttpPort:    resolvedPort(ctx, standards.REST),
		EndpointConnectPort: resolvedPort(ctx, standards.CONNECT),
	}
	// The module authority endpoint is declared in service.codefly.yaml, and a
	// topology that omits it — or gives it a port another listener already
	// binds — is refused by the deployment generator, so a COMPOSITION error is
	// caught at render (cataloggen.validateModuleAuthorityEndpoint). An address
	// that does not resolve here is a different failure: the runtime, or the
	// service agent's rendered Deployment, injected no capability for this
	// endpoint. Binding no listener leaves it unreachable — connection refused,
	// never a weaker gate, and RunAuthority already treats a nil port that way.
	// Panicking instead would trade an auxiliary listener for the whole host:
	// accounts would crashloop and take the tenant surfaces, the internal tier
	// and every service that authenticates through them down with it.
	//
	// Like the two above, this query never invents a port: the only outcomes are
	// the injected address or this error path.
	if authority, resolveErr := codefly.For(ctx).Endpoint(business.ModuleAuthorityEndpoint).API(standards.GRPC).ResolveNetworkInstance(); resolveErr != nil {
		wool.Get(ctx).In("main").Error(
			"the module authority endpoint did not resolve; no module authority listener is served",
			wool.Field("endpoint", business.ModuleAuthorityEndpoint),
			wool.ErrField(resolveErr),
		)
	} else {
		config.EndpointAuthorityPort = shared.Pointer(authority.Port)
	}

	// Complete dependency wiring, plugin registration and fixture seeding before
	// opening any listener. Starting the generated server first exposes handlers
	// while the package-level business service is still nil and makes a passing
	// port probe race with application readiness.
	if work != nil {
		clean, err := work(ctx)
		if err != nil {
			panic(err)
		}
		if clean != nil {
			defer clean()
		}
	}

	server, err := adapters.NewServer(config)
	if err != nil {
		panic(err)
	}

	go func() {
		if startErr := server.Start(context.Background()); startErr != nil {
			panic(startErr)
		}
	}()

	<-ctx.Done()
	server.Stop()
	fmt.Println("got interruption signal")

}
